[package]
name = "zea-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
zea-parser = {path = "../zea-parser"}
zea-ipr = {path = "../zea-ipr"}
zea-common = {path = "../zea-common"}
zea-codegen = {path="../zea-codegen"}
log = { version = "0.4.33", features = ["std"] }
colog = "1.4.0"
tempfile = "3.27.0"
