//! GENERATED BY OPENCODE DEEPSEEK FLASH V4 FREE cuz i'm too lazy to write the parser myself
//!
//! Pretty-printed AST parser — parses the indentation-based format produced by
//! `zea_ast::visualization::IndentPrint` back into AST nodes.
//!
//! ## Format conventions
//!
//! Every line has an implicit *depth* computed from its leading spaces divided
//! by 2 (each indent level = 2 spaces).  The printer puts:
//!
//! - The opening token (e.g. `module`, `func` \`name\` , `block`, `call`,
//!   `branch`, `init_packed`, `(`, `)`) at the node's own depth.
//! - `.field` labels at `depth + 1`.
//! - Field *values* at `depth + 2`.
//! - List items at list depth with a `- ` prefix.
//!
//! There are no closing tags — scope is determined entirely by indentation.
//! A line at a shallower (or equal) depth than the current node signals the
//! end of that node.
//!
//! ## Parser design
//!
//! The parser pre-computes `(depth, content)` pairs for every non‑empty line
//! and then uses recursive descent.  Each `parse_xxx(depth)` method expects
//! the opening token (if any) to have **already been consumed** by the caller,
//! so it starts reading children directly.  The only exception is
//! `parse_block_expr` which also assumes the `block` token is already consumed.
//!
//! All parsed nodes receive `NodeId::sentinel()`; the labeler is run afterward.

use std::fmt;
use zea_ast::zea::{
    AssignmentPattern, BinOp, BlockExpression, Expression, ExpressionKind, FuncParam, Function,
    FunctionCall, IfThenElse, InitializationBlock, InitializationKind, Module, NodeId,
    PackedInitialization, SimpleInitialization, Statement, StatementKind, TypeSpecifier, UnOp,
};

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

/// Errors produced during pretty-print parsing.
#[derive(Debug)]
pub enum ParseError {
    /// A line was found that does not match what the parser expected.
    UnexpectedToken {
        expected: String,
        found: String,
        line: usize,
    },
    /// The input ended before the parser could find what it needed.
    UnexpectedEndOfInput { expected: String },
}

impl fmt::Display for ParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ParseError::UnexpectedToken {
                expected,
                found,
                line,
            } => write!(f, "line {line}: expected {expected}, found {found}"),
            ParseError::UnexpectedEndOfInput { expected } => {
                write!(f, "unexpected end of input, expected {expected}")
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Free helpers — node construction (all use NodeId::sentinel())
// ---------------------------------------------------------------------------

fn expr_binop(op: BinOp, left: Expression, right: Expression) -> Expression {
    Expression {
        id: NodeId::sentinel(),
        kind: ExpressionKind::BinOpExpr(op, Box::new(left), Box::new(right)),
    }
}
fn expr_unop(op: UnOp, arg: Expression) -> Expression {
    Expression {
        id: NodeId::sentinel(),
        kind: ExpressionKind::UnOpExpr(op, Box::new(arg)),
    }
}
fn expr_member_access(subject: Expression, field: String) -> Expression {
    Expression {
        id: NodeId::sentinel(),
        kind: ExpressionKind::MemberAccess(Box::new(subject), field),
    }
}
fn expr_block(block: BlockExpression) -> Expression {
    Expression {
        id: NodeId::sentinel(),
        kind: ExpressionKind::Block(Box::new(block)),
    }
}

fn stmt_ret(expr: Expression) -> Statement {
    Statement {
        id: NodeId::sentinel(),
        kind: StatementKind::Return(expr),
    }
}
fn stmt_tail(expr: Expression) -> Statement {
    Statement {
        id: NodeId::sentinel(),
        kind: StatementKind::BlockTail(expr),
    }
}
fn stmt_block(block: BlockExpression) -> Statement {
    Statement {
        id: NodeId::sentinel(),
        kind: StatementKind::Block(block),
    }
}
fn stmt_call(call: FunctionCall) -> Statement {
    Statement {
        id: NodeId::sentinel(),
        kind: StatementKind::FunctionCall(call),
    }
}
fn stmt_init_packed(packed: PackedInitialization) -> Statement {
    Statement {
        id: NodeId::sentinel(),
        kind: StatementKind::Initialization(init_packed(packed)),
    }
}
fn stmt_init_unpacked(inits: Vec<SimpleInitialization>) -> Statement {
    Statement {
        id: NodeId::sentinel(),
        kind: StatementKind::Initialization(init_unpacked(inits)),
    }
}
fn stmt_if_then_else(ite: IfThenElse) -> Statement {
    Statement {
        id: NodeId::sentinel(),
        kind: StatementKind::IfThenElse(ite),
    }
}

fn init_packed(packed: PackedInitialization) -> InitializationBlock {
    InitializationBlock {
        id: NodeId::sentinel(),
        kind: InitializationKind::Packed(packed),
    }
}
fn init_unpacked(inits: Vec<SimpleInitialization>) -> InitializationBlock {
    InitializationBlock {
        id: NodeId::sentinel(),
        kind: InitializationKind::Unpacked(inits),
    }
}

fn err_unexpected(expected: &str, found: &str, line: usize) -> ParseError {
    ParseError::UnexpectedToken {
        expected: expected.into(),
        found: found.into(),
        line,
    }
}

// ---------------------------------------------------------------------------
// Parser struct
// ---------------------------------------------------------------------------

/// Recursive-descent parser for the indentation-based pretty-printed AST format.
///
/// Input is pre-processed into a vector of `(depth, trimmed_content)` pairs.
/// A *depth* of `n` means the line is preceded by `n * 2` spaces.
struct ZeaPrettyAstParser<'a> {
    /// Pre-computed lines: `(depth, content)`.
    lines: Vec<(usize, &'a str)>,
    /// Current read position.
    cursor: usize,
}

/// Parse a full `Module` from the pretty-printed source string.
pub fn parse_module(src: &str) -> Module {
    _parse_module(src).unwrap_or_else(|e| panic!("{e}"))
}
fn _parse_module(src: &str) -> Result<Module, ParseError> {
    let mut p = ZeaPrettyAstParser::new(src);
    let m = p.parse_module_inner()?;
    p.expect_end()?;
    Ok(m)
}

/// Parse a bare expression.
///
/// The source should contain exactly one expression at depth 0:
/// ```text
/// lit_int(42)
/// ```
/// or
/// ```text
/// block
///   - return
///     lit_int(1)
///   @unit
/// ```
pub fn parse_expression(src: &str) -> Expression {
    _parse_expression(src).unwrap_or_else(|e| panic!("{e}"))
}
fn _parse_expression(src: &str) -> Result<Expression, ParseError> {
    let mut p = ZeaPrettyAstParser::new(src);
    let expr = p.parse_expr(0)?;
    p.expect_end()?;
    Ok(expr)
}
/// Parse a bare block expression.
///
/// The source must start with `block` at depth 0:
/// ```text
/// block
///   - return
///     lit_int(1)
///   @unit
/// ```
pub fn parse_block(src: &str) -> BlockExpression {
    _parse_block(src).unwrap_or_else(|e| panic!("{e}"))
}

fn _parse_block(src: &str) -> Result<BlockExpression, ParseError> {
    let mut p = ZeaPrettyAstParser::new(src);
    p.expect_line(0, "block")?;
    let block = p.parse_block_expr(0)?;
    p.expect_end()?;
    Ok(block)
}
/// Parse a bare statement.
///
/// The source must start with `- <kind>` at depth 0:
/// ```text
/// - return
///   lit_int(42)
/// ```
pub fn parse_statement(src: &str) -> Statement {
    _parse_statement(src).unwrap_or_else(|e| panic!("{e}"))
}

fn _parse_statement(src: &str) -> Result<Statement, ParseError> {
    let mut p = ZeaPrettyAstParser::new(src);
    let (d, c) = p.peek().ok_or(ParseError::UnexpectedEndOfInput {
        expected: "statement starting with `- `".into(),
    })?;
    if d != 0 || !c.starts_with("- ") {
        return Err(err_unexpected(
            "statement starting with `- <kind>` at depth 0",
            &format!("`{c}` at depth {d}"),
            0,
        ));
    }
    p.advance();
    let stmt = p.parse_stmt_content(&c[2..], 0)?;
    p.expect_end()?;
    Ok(stmt)
}
impl<'a> ZeaPrettyAstParser<'a> {
    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /// Pre-process the source: split into non‑empty lines, compute depths.
    ///
    /// The depth of a line is `leading_spaces / 2`.
    fn new(src: &'a str) -> Self {
        let lines: Vec<_> = src
            .lines()
            .filter(|l| !l.trim().is_empty())
            .map(|l| {
                let trimmed = l.trim_start();
                let indent = l.len() - trimmed.len();
                (indent / 2, trimmed)
            })
            .collect();
        Self { lines, cursor: 0 }
    }

    /// Return the `(depth, content)` of the current line, or `None` at EOF.
    fn peek(&self) -> Option<(usize, &'a str)> {
        self.lines.get(self.cursor).copied()
    }

    /// Advance the cursor by one line.
    fn advance(&mut self) {
        self.cursor += 1;
    }

    /// Number of remaining unprocessed lines.
    fn remaining(&self) -> usize {
        self.lines.len().saturating_sub(self.cursor)
    }

    /// Depth of the current line (0 if at EOF).
    fn current_depth(&self) -> usize {
        self.peek().map_or(0, |(d, _)| d)
    }

    /// Check that we are at the end of input.
    fn expect_end(&self) -> Result<(), ParseError> {
        if self.remaining() == 0 {
            Ok(())
        } else {
            let (d, c) = self.peek().unwrap();
            Err(err_unexpected(
                "end of input",
                &format!("`{c}` at depth {d}"),
                self.cursor,
            ))
        }
    }

    /// Expect the next line to have exactly `depth` and content `content`.
    /// Advances past it on success.
    fn expect_line(&mut self, depth: usize, content: &str) -> Result<(), ParseError> {
        match self.peek() {
            Some((d, c)) if d == depth && c == content => {
                self.advance();
                Ok(())
            }
            Some((d, c)) => Err(err_unexpected(
                &format!("`{content}` at depth {depth}"),
                &format!("`{c}` at depth {d}"),
                self.cursor,
            )),
            None => Err(ParseError::UnexpectedEndOfInput {
                expected: format!("`{content}` at depth {depth}"),
            }),
        }
    }

    /// Peek at the next line and check if it is `.name` at `depth`.
    fn peek_field(&self, name: &str, depth: usize) -> bool {
        self.peek()
            .map_or(false, |(d, c)| d == depth && c == &format!(".{name}"))
    }

    /// Expect the current line to be at `depth`. Return its content without
    /// advancing.
    fn expect_at_depth(&mut self, depth: usize, desc: &str) -> Result<&'a str, ParseError> {
        let (d, content) = self.peek().ok_or(ParseError::UnexpectedEndOfInput {
            expected: format!("{desc} at depth {depth}"),
        })?;
        if d != depth {
            return Err(err_unexpected(
                &format!("{desc} at depth {depth}"),
                &format!("`{content}` at depth {d}"),
                self.cursor,
            ));
        }
        Ok(content)
    }

    /// Read the next line as a raw string at the given depth.
    fn parse_string_at(&mut self, depth: usize) -> Result<String, ParseError> {
        let content = self.expect_at_depth(depth, "string value")?;
        self.advance();
        Ok(content.to_string())
    }

    // -----------------------------------------------------------------------
    // Module
    // -----------------------------------------------------------------------

    /// Parse a module.
    ///
    /// Expected layout:
    /// ```text
    /// module              -- depth 0
    ///   .imports          -- depth 1
    ///   .exports          -- depth 1
    ///   .globs            -- depth 1
    ///   .funcs            -- depth 1
    /// ```
    fn parse_module_inner(&mut self) -> Result<Module, ParseError> {
        self.expect_line(0, "module")?;
        let imports = self.parse_field_list("imports", |p, c, _d| Ok(c.to_string()))?;
        let exports = self.parse_field_list("exports", |p, c, _d| Ok(c.to_string()))?;
        let globs = self.parse_field_list("globs", |p, c, d| p.parse_init_from_content(c, d))?;
        let funcs = self.parse_field_list("funcs", |p, c, d| p.parse_func_from_content(c, d))?;
        Ok(Module {
            id: NodeId::sentinel(),
            imports,
            exports,
            global_vars: globs,
            functions: funcs,
            struct_definitions: vec![],
        })
    }

    // -----------------------------------------------------------------------
    // Generic field-list parser
    // -----------------------------------------------------------------------

    /// Parse a `.name` field containing a list of `- <item>` entries.
    /// Each entry is parsed by `parse_item(parser, content_after_dash, depth)`.
    fn parse_field_list<T>(
        &mut self,
        name: &str,
        mut parse_item: impl FnMut(&mut Self, &str, usize) -> Result<T, ParseError>,
    ) -> Result<Vec<T>, ParseError> {
        let depth = self.current_depth();
        self.expect_line(depth, &format!(".{name}"))?;
        let mut items = Vec::new();
        loop {
            match self.peek() {
                Some((d, c)) if d == depth + 1 && c.starts_with("- ") => {
                    self.advance();
                    items.push(parse_item(self, &c[2..], depth + 1)?);
                }
                _ => return Ok(items),
            }
        }
    }

    // -----------------------------------------------------------------------
    // init_packed / init_unpacked_block
    // -----------------------------------------------------------------------

    /// Dispatch to `init_packed` or `init_unpacked_block` based on content.
    fn parse_init_from_content(
        &mut self,
        kind: &str,
        depth: usize,
    ) -> Result<InitializationBlock, ParseError> {
        match kind {
            "init_packed" => Ok(init_packed(self.parse_packed_init(depth)?)),
            "init_unpacked_block" => Ok(init_unpacked(self.parse_init_unpacked_list(depth)?)),
            "init" => Ok(init_unpacked(vec![self.parse_simple_init(depth)?])),
            _ => Err(err_unexpected(
                "init_packed or init_unpacked_block",
                kind,
                self.cursor,
            )),
        }
    }

    /// Parse a packed initialization (`init_packed`).
    ///
    /// Layout:
    /// ```text
    /// init_packed         -- depth (already consumed by caller)
    ///   .pattern          -- depth + 1
    ///     <assignee>      -- depth + 2
    ///   .type             -- depth + 1
    ///     <type>          -- depth + 2
    ///   .value            -- depth + 1
    ///     <expr>          -- depth + 2
    /// ```
    fn parse_packed_init(&mut self, depth: usize) -> Result<PackedInitialization, ParseError> {
        self.expect_line(depth + 1, ".pattern")?;
        let assignee = self.parse_assign_pattern(depth + 2)?;
        self.expect_line(depth + 1, ".type")?;
        let typ = self.parse_type_opt(depth + 2)?;
        self.expect_line(depth + 1, ".value")?;
        let value = self.parse_expr(depth + 2)?;
        Ok(PackedInitialization {
            assignee,
            typ,
            value,
        })
    }

    /// Parse a list of simple initializations (`init_unpacked_block`).
    ///
    /// Layout:
    /// ```text
    /// init_unpacked_block  -- depth (already consumed)
    ///   - init             -- depth + 1
    ///       .assignee      -- depth + 2
    ///         <name>       -- depth + 3
    ///       ...
    /// ```
    fn parse_init_unpacked_list(
        &mut self,
        depth: usize,
    ) -> Result<Vec<SimpleInitialization>, ParseError> {
        let mut items = Vec::new();
        loop {
            match self.peek() {
                Some((d, c)) if d == depth + 1 && c.starts_with("- init") => {
                    self.advance();
                    items.push(self.parse_simple_init(depth + 1)?);
                }
                _ => return Ok(items),
            }
        }
    }

    /// Parse a simple initialization (`init`) inside an unpacked block.
    ///
    /// Layout:
    /// ```text
    /// init                -- depth (already consumed)
    ///   .assignee         -- depth + 1
    ///     <name>          -- depth + 2
    ///   .type             -- depth + 1
    ///     <type>          -- depth + 2
    ///   .value            -- depth + 1
    ///     <expr>          -- depth + 2
    /// ```
    fn parse_simple_init(&mut self, depth: usize) -> Result<SimpleInitialization, ParseError> {
        self.expect_line(depth + 1, ".assignee")?;
        let assignee = self.parse_string_at(depth + 2)?;
        self.expect_line(depth + 1, ".type")?;
        let typ = self.parse_type_opt(depth + 2)?;
        self.expect_line(depth + 1, ".value")?;
        let value = self.parse_expr(depth + 2)?;
        Ok(SimpleInitialization {
            id: NodeId::sentinel(),
            assignee,
            typ,
            value,
        })
    }

    // -----------------------------------------------------------------------
    // Assignment patterns (for destructuring)
    // -----------------------------------------------------------------------

    /// Parse an assignment pattern — either a bare identifier or a `(..)` tuple.
    ///
    /// Layout:
    /// ```text
    /// (                   -- depth
    ///   <pat>             -- depth + 1
    ///   <pat>             -- depth + 1
    /// )                   -- depth
    /// ```
    fn parse_assign_pattern(&mut self, depth: usize) -> Result<AssignmentPattern, ParseError> {
        let content = self.expect_at_depth(depth, "assignment pattern")?;
        if content == "(" {
            self.advance();
            let mut pats = Vec::new();
            loop {
                match self.peek() {
                    // Closing paren is at the same depth as the opening one.
                    Some((dd, cc)) if dd == depth && cc == ")" => {
                        self.advance();
                        return Ok(AssignmentPattern::Tuple(pats));
                    }
                    // Sub-patterns are one level deeper.
                    Some((dd, _)) if dd == depth + 1 => {
                        pats.push(self.parse_assign_pattern(depth + 1)?);
                    }
                    Some((dd, cc)) => {
                        return Err(err_unexpected(
                            &format!("sub-pattern at depth {}", depth + 1),
                            &format!("`{cc}` at depth {dd}"),
                            self.cursor,
                        ));
                    }
                    None => {
                        return Err(ParseError::UnexpectedEndOfInput {
                            expected: "`)`".into(),
                        });
                    }
                }
            }
        } else {
            self.advance();
            Ok(AssignmentPattern::Identifier(content.to_string()))
        }
    }

    // -----------------------------------------------------------------------
    // Type specifiers
    // -----------------------------------------------------------------------

    /// Parse an optional type annotation.
    ///
    /// The special string `@unknown` represents `None`.
    /// Everything else is delegated to `parse_type_string`.
    fn parse_type_opt(&mut self, depth: usize) -> Result<Option<TypeSpecifier>, ParseError> {
        let content = self.expect_at_depth(depth, "type")?;
        if content == "@unknown" {
            self.advance();
            return Ok(None);
        }
        self.advance();
        Ok(Some(parse_type_string(content)))
    }

    // -----------------------------------------------------------------------
    // Functions & params
    // -----------------------------------------------------------------------

    /// Strip the `func \`name\`` wrapper and delegate to `parse_func_body`.
    fn parse_func_from_content(
        &mut self,
        kind: &str,
        depth: usize,
    ) -> Result<Function, ParseError> {
        let name = kind
            .strip_prefix("func `")
            .and_then(|s| s.strip_suffix('`'))
            .ok_or_else(|| err_unexpected("func `name`", kind, self.cursor))?;
        self.parse_func_body(name.to_string(), depth)
    }

    /// Parse a function body.
    ///
    /// Layout (after `func \`name\`` has been consumed):
    /// ```text
    ///   .returns          -- depth + 1
    ///     <type>          -- depth + 2
    ///   .params           -- depth + 1
    ///     - .param        -- depth + 2
    ///         <name>      -- depth + 3
    ///         <type>      -- depth + 3
    ///   .body             -- depth + 1
    ///     block           -- depth + 2
    ///       ...           -- depth + 3
    /// ```
    fn parse_func_body(&mut self, name: String, depth: usize) -> Result<Function, ParseError> {
        self.expect_line(depth + 1, ".returns")?;
        let returns = self
            .parse_type_opt(depth + 2)?
            .unwrap_or(TypeSpecifier::Unit);

        self.expect_line(depth + 1, ".params")?;
        let params = self.parse_param_list(depth + 2)?;

        self.expect_line(depth + 1, ".body")?;
        self.expect_line(depth + 2, "block")?;
        let body = self.parse_block_expr(depth + 2)?;

        Ok(Function {
            id: NodeId::sentinel(),
            name,
            params,
            returns,
            body,
        })
    }

    /// Parse the parameter list of a function.
    ///
    /// Each parameter is introduced by `- .param` at the given `depth`.
    fn parse_param_list(&mut self, depth: usize) -> Result<Vec<FuncParam>, ParseError> {
        let mut items = Vec::new();
        loop {
            match self.peek() {
                Some((d, c)) if d == depth && c.starts_with("- ") => {
                    self.advance();
                    let content = &c[2..];
                    if content != ".param" {
                        return Err(err_unexpected(".param", content, self.cursor));
                    }
                    items.push(self.parse_func_param(depth)?);
                }
                _ => return Ok(items),
            }
        }
    }

    /// Parse a single function parameter.
    ///
    /// Layout:
    /// ```text
    /// .param              -- depth (already consumed)
    ///   <name>            -- depth + 1
    ///   <type>            -- depth + 1
    /// ```
    fn parse_func_param(&mut self, depth: usize) -> Result<FuncParam, ParseError> {
        let name = self.parse_string_at(depth + 1)?;
        let typ = self.parse_type_opt(depth + 1)?;
        Ok(FuncParam {
            id: NodeId::sentinel(),
            name,
            typ: typ.unwrap_or(TypeSpecifier::Unit),
        })
    }

    // -----------------------------------------------------------------------
    // Statements
    // -----------------------------------------------------------------------

    /// Parse a statement given its kind string (the content after `- `).
    ///
    /// `depth` is the depth of the `- <kind>` line itself.
    fn parse_stmt_content(&mut self, kind: &str, depth: usize) -> Result<Statement, ParseError> {
        match kind {
            "return" => Ok(stmt_ret(self.parse_expr(depth + 1)?)),
            "tail" => Ok(stmt_tail(self.parse_expr(depth + 1)?)),
            "init_packed" => Ok(stmt_init_packed(self.parse_packed_init(depth)?)),
            "init_unpacked_block" => Ok(stmt_init_unpacked(self.parse_init_unpacked_list(depth)?)),
            "branch" => Ok(stmt_if_then_else(self.parse_branch(depth)?)),
            "block" => Ok(stmt_block(self.parse_block_expr(depth)?)),
            "call" => Ok(stmt_call(self.parse_call(depth)?)),
            _ => Err(err_unexpected(
                "statement kind (return, tail, init_packed, init_unpacked_block, branch, block, call)",
                kind,
                self.cursor,
            )),
        }
    }

    // -----------------------------------------------------------------------
    // Expressions
    // -----------------------------------------------------------------------

    /// Parse any expression at the given depth.
    ///
    /// Consumes the current line, then delegates to [`parse_expr_content`].
    fn parse_expr(&mut self, depth: usize) -> Result<Expression, ParseError> {
        let content = self.expect_at_depth(depth, "expression")?;
        let line = self.cursor;
        self.advance();
        self.parse_expr_content(content, depth, line)
    }

    /// Inner dispatch after the opening line has been consumed.
    ///
    /// - Leaf forms (`ident(…)`, `lit_int(…)`, `lit_float(…)`, `@unit`)
    ///   are handled from `content` alone.
    /// - Compound forms (`block`, `branch`, `call`, `expr_member`,
    ///   `operator\`…\``) advance further to read children.
    ///
    /// `line` is the source line number for error messages.
    fn parse_expr_content(
        &mut self,
        content: &str,
        depth: usize,
        line: usize,
    ) -> Result<Expression, ParseError> {
        // ident("name")
        if let Some(name) = content.strip_prefix("ident(") {
            let ident = name
                .strip_suffix(')')
                .ok_or_else(|| err_unexpected("ident(name)", content, line))?;
            return Ok(Expression::ident(ident.to_string()));
        }

        // lit_int(123)
        if let Some(num) = content.strip_prefix("lit_int(") {
            let n = num
                .strip_suffix(')')
                .ok_or_else(|| err_unexpected("lit_int(n)", content, line))?;
            let val: usize = n
                .parse()
                .map_err(|_| err_unexpected("integer literal", content, line))?;
            return Ok(Expression::wrap_lit_int(val));
        }

        // lit_float(3.14)
        if let Some(num) = content.strip_prefix("lit_float(") {
            let n = num
                .strip_suffix(')')
                .ok_or_else(|| err_unexpected("lit_float(n)", content, line))?;
            let val: f64 = n
                .parse()
                .map_err(|_| err_unexpected("float literal", content, line))?;
            return Ok(Expression::wrap_lit_float(val));
        }

        // Keywords / compound expressions
        match content {
            "@unit" => return Ok(Expression::unit()),
            "block" => {
                let block = self.parse_block_expr(depth)?;
                return Ok(expr_block(block));
            }
            "branch" => {
                let branch = self.parse_branch(depth)?;
                return Ok(branch.wrap_in_expression());
            }
            "call" => {
                let call = self.parse_call(depth)?;
                return Ok(call.wrap_in_expression());
            }
            "expr_member" => {
                let expr = self.parse_expr_member(depth)?;
                return Ok(expr);
            }
            _ => {}
        }

        // operator`Name`
        if let Some(op_name) = content.strip_prefix("operator`") {
            let op = op_name
                .strip_suffix('`')
                .ok_or_else(|| err_unexpected("operator`Name`", content, line))?;
            return self.parse_operator_expr(op, depth);
        }

        Err(err_unexpected("expression", content, line))
    }

    /// Parse a binary- or unary-operator expression.
    ///
    /// For binary operators (add, sub, eq, …):
    /// ```text
    /// operator`Add`        -- depth (already consumed)
    ///   <left>             -- depth + 1
    ///   <right>            -- depth + 1
    /// ```
    ///
    /// For unary operators (neg, lognot, …):
    /// ```text
    /// operator`Neg`        -- depth (already consumed)
    ///   <arg>              -- depth + 1
    /// ```
    fn parse_operator_expr(&mut self, op: &str, depth: usize) -> Result<Expression, ParseError> {
        if is_binop(op) {
            let binop = parse_binop(op)?;
            let left = self.parse_expr(depth + 1)?;
            let right = self.parse_expr(depth + 1)?;
            Ok(expr_binop(binop, left, right))
        } else {
            let unop = parse_unop(op)?;
            let arg = self.parse_expr(depth + 1)?;
            Ok(expr_unop(unop, arg))
        }
    }

    /// Parse a member-access expression.
    ///
    /// Layout:
    /// ```text
    /// expr_member          -- depth (already consumed)
    ///   <subject>          -- depth + 1
    ///   .member            -- depth + 1
    ///     <field_name>     -- depth + 2
    /// ```
    fn parse_expr_member(&mut self, depth: usize) -> Result<Expression, ParseError> {
        let expr = self.parse_expr(depth + 1)?;
        self.expect_line(depth + 1, ".member")?;
        let member = self.parse_string_at(depth + 2)?;
        Ok(expr_member_access(expr, member))
    }

    // -----------------------------------------------------------------------
    // Block expressions
    // -----------------------------------------------------------------------

    /// Parse a block expression.
    ///
    /// The `block` token is consumed by the caller.
    /// Children live at `depth + 1`:
    /// - Lines starting with `- ` are statements.
    /// - A line without `- ` is the block's last expression.
    /// - A line at a shallower depth signals an implicit `()` last expression.
    fn parse_block_expr(&mut self, depth: usize) -> Result<BlockExpression, ParseError> {
        let mut statements = Vec::new();
        loop {
            match self.peek() {
                // Statement: `- <kind>`
                Some((d, c)) if d == depth + 1 && c.starts_with("- ") => {
                    self.advance();
                    let content = &c[2..];
                    statements.push(self.parse_stmt_content(content, depth + 1)?);
                }
                // Last expression (no `- ` prefix)
                Some((d, _)) if d == depth + 1 => {
                    let expr = self.parse_expr(depth + 1)?;
                    return Ok(BlockExpression {
                        id: NodeId::sentinel(),
                        statements,
                        last: expr,
                    });
                }
                // Content ended (shallower depth or EOF) → implicit unit
                Some((d, _)) if d < depth + 1 => {
                    return Ok(BlockExpression {
                        id: NodeId::sentinel(),
                        statements,
                        last: Expression::unit(),
                    });
                }
                Some(_) => {
                    let (_d, c) = self.peek().unwrap();
                    return Err(err_unexpected(
                        &format!("statement at depth {}", depth + 1),
                        &format!("`{c}` at depth {}", self.peek().unwrap().0),
                        self.cursor,
                    ));
                }
                None => {
                    return Ok(BlockExpression {
                        id: NodeId::sentinel(),
                        statements,
                        last: Expression::unit(),
                    });
                }
            }
        }
    }

    // -----------------------------------------------------------------------
    // If-then-else (branch)
    // -----------------------------------------------------------------------

    /// Parse an if-then-else expression.
    ///
    /// Layout (after `branch` consumed):
    /// ```text
    ///   .cond              -- depth + 1
    ///     <condition>      -- depth + 2
    ///   .then              -- depth + 1
    ///     <true_case>      -- depth + 2
    ///   .otherwise         -- depth + 1  (optional)
    ///     <false_case>     -- depth + 2
    /// ```
    fn parse_branch(&mut self, depth: usize) -> Result<IfThenElse, ParseError> {
        self.expect_line(depth + 1, ".cond")?;
        let condition = self.parse_expr(depth + 2)?;
        self.expect_line(depth + 1, ".then")?;
        let true_case = self.parse_expr(depth + 2)?;
        let false_case = if self.peek_field("otherwise", depth + 1) {
            self.advance();
            Some(Box::new(self.parse_expr(depth + 2)?))
        } else {
            None
        };
        Ok(IfThenElse {
            id: NodeId::sentinel(),
            condition: Box::new(condition),
            true_case: Box::new(true_case),
            false_case,
        })
    }

    // -----------------------------------------------------------------------
    // Function calls
    // -----------------------------------------------------------------------

    /// Parse a function-call expression.
    ///
    /// Layout (after `call` consumed):
    /// ```text
    ///   .subject           -- depth + 1
    ///     <expr>           -- depth + 2
    ///   .args              -- depth + 1  (optional)
    ///     - <arg>          -- depth + 2
    ///     - <arg>          -- depth + 2
    /// ```
    fn parse_call(&mut self, depth: usize) -> Result<FunctionCall, ParseError> {
        self.expect_line(depth + 1, ".subject")?;
        let subject = self.parse_expr(depth + 2)?;
        let args = if self.peek_field("args", depth + 1) {
            self.advance();
            self.parse_expr_list(depth + 2)?
        } else {
            Vec::new()
        };
        Ok(FunctionCall {
            id: NodeId::sentinel(),
            subject: Box::new(subject),
            args,
        })
    }

    /// Parse a list of `- <expr>` items at the given depth.
    fn parse_expr_list(&mut self, depth: usize) -> Result<Vec<Expression>, ParseError> {
        let mut items = Vec::new();
        loop {
            match self.peek() {
                Some((d, c)) if d == depth && c.starts_with("- ") => {
                    let line = self.cursor;
                    self.advance();
                    let expr = self.parse_expr_content(&c[2..], depth, line)?;
                    items.push(expr);
                }
                _ => return Ok(items),
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Type name parser (free function)
// ---------------------------------------------------------------------------

/// Convert a type-name string from the pretty-print format into a
/// `TypeSpecifier`.
///
/// Recognised forms:
/// - `()` → `Unit`
/// - `!` → `Never`
/// - `Bool` → `Bool`
/// - `&<inner>` → `Pointer(Box<inner>)`
/// - `[<inner>]` → `ArrayOf(Box<inner>)`
/// - `i<width>` → `Integer { width, signed: true }`
/// - `u<width>` → `Integer { width, signed: false }`
/// - `f<width>` → `Float { width }`
/// - Everything else → `Basic(name)`
fn parse_type_string(s: &str) -> TypeSpecifier {
    match s {
        "()" => return TypeSpecifier::Unit,
        "!" => return TypeSpecifier::Never,
        "Bool" => return TypeSpecifier::Bool,
        _ => {}
    }
    if s.starts_with('&') {
        let inner = parse_type_string(&s[1..]);
        return TypeSpecifier::Pointer(Box::new(inner));
    }
    if s.starts_with('[') && s.ends_with(']') {
        let inner = parse_type_string(&s[1..s.len() - 1]);
        return TypeSpecifier::ArrayOf(Box::new(inner));
    }
    if let Some(w) = s.strip_prefix('i') {
        if let Ok(width) = w.parse::<usize>() {
            return TypeSpecifier::Integer {
                width,
                signed: true,
            };
        }
    }
    if let Some(w) = s.strip_prefix('u') {
        if let Ok(width) = w.parse::<usize>() {
            return TypeSpecifier::Integer {
                width,
                signed: false,
            };
        }
    }
    if let Some(w) = s.strip_prefix('f') {
        if let Ok(width) = w.parse::<usize>() {
            return TypeSpecifier::Float { width };
        }
    }
    TypeSpecifier::NonScalar(s.to_string())
}

// ---------------------------------------------------------------------------
// Operator-name helpers
// ---------------------------------------------------------------------------

/// Returns `true` when `s` is a recognised binary-operator name.
fn is_binop(s: &str) -> bool {
    matches!(
        s,
        "Add"
            | "Sub"
            | "Mul"
            | "Div"
            | "Mod"
            | "LogAnd"
            | "LogOr"
            | "LogXor"
            | "BitAnd"
            | "BitOr"
            | "BitXor"
            | "Subscript"
            | "Lsh"
            | "Rsh"
            | "Eq"
            | "Neq"
            | "Geq"
            | "Leq"
            | "LT"
            | "GT"
    )
}

/// Convert a binary-operator name to its AST variant.
fn parse_binop(s: &str) -> Result<BinOp, ParseError> {
    match s {
        "Add" => Ok(BinOp::Add),
        "Sub" => Ok(BinOp::Sub),
        "Mul" => Ok(BinOp::Mul),
        "Div" => Ok(BinOp::Div),
        "Mod" => Ok(BinOp::Mod),
        "LogAnd" => Ok(BinOp::LogAnd),
        "LogOr" => Ok(BinOp::LogOr),
        "LogXor" => Ok(BinOp::LogXor),
        "BitAnd" => Ok(BinOp::BitAnd),
        "BitOr" => Ok(BinOp::BitOr),
        "BitXor" => Ok(BinOp::BitXor),
        "Subscript" => Ok(BinOp::Subscript),
        "Lsh" => Ok(BinOp::Lsh),
        "Rsh" => Ok(BinOp::Rsh),
        "Eq" => Ok(BinOp::Eq),
        "Neq" => Ok(BinOp::Neq),
        "Geq" => Ok(BinOp::Geq),
        "Leq" => Ok(BinOp::Leq),
        "LT" => Ok(BinOp::LT),
        "GT" => Ok(BinOp::GT),
        _ => Err(err_unexpected("binary operator", s, 0)),
    }
}

/// Convert a unary-operator name to its AST variant.
fn parse_unop(s: &str) -> Result<UnOp, ParseError> {
    match s {
        "Neg" => Ok(UnOp::Neg),
        "LogNot" => Ok(UnOp::LogNot),
        "BitNot" => Ok(UnOp::BitNot),
        _ => Err(err_unexpected("unary operator (Neg, LogNot, BitNot)", s, 0)),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use zea_ast::helper_impls::StructuralEq;
    use zea_ast::visualisation::IndentPrint;

    // ---- test builder helpers ------------------------------------------------

    fn module_(funcs: Vec<Function>) -> Module {
        Module {
            id: NodeId::sentinel(),
            imports: vec![],
            exports: vec![],
            global_vars: vec![],
            functions: funcs,
            struct_definitions: vec![],
        }
    }

    fn function(
        name: &str,
        params: Vec<FuncParam>,
        returns: TypeSpecifier,
        body: BlockExpression,
    ) -> Function {
        Function {
            id: NodeId::sentinel(),
            name: name.into(),
            params,
            returns,
            body,
        }
    }

    fn param(name: &str, typ: TypeSpecifier) -> FuncParam {
        FuncParam {
            id: NodeId::sentinel(),
            name: name.into(),
            typ,
        }
    }

    fn block(stmts: Vec<Statement>, last: Expression) -> BlockExpression {
        BlockExpression {
            id: NodeId::sentinel(),
            statements: stmts,
            last,
        }
    }

    fn expr_ident(name: &str) -> Expression {
        Expression::ident(name.to_owned())
    }
    fn expr_int(n: usize) -> Expression {
        Expression::wrap_lit_int(n)
    }
    fn expr_float(f: f64) -> Expression {
        Expression::wrap_lit_float(f)
    }
    fn expr_unit() -> Expression {
        Expression::unit()
    }
    fn expr_binop(op: BinOp, left: Expression, right: Expression) -> Expression {
        Expression {
            id: NodeId::sentinel(),
            kind: ExpressionKind::BinOpExpr(op, Box::new(left), Box::new(right)),
        }
    }
    fn expr_member(subject: Expression, field: &str) -> Expression {
        Expression {
            id: NodeId::sentinel(),
            kind: ExpressionKind::MemberAccess(Box::new(subject), field.to_owned()),
        }
    }
    fn expr_call(subject: Expression, args: Vec<Expression>) -> Expression {
        FunctionCall {
            id: NodeId::sentinel(),
            subject: Box::new(subject),
            args,
        }
        .wrap_in_expression()
    }

    fn call_stmt(subject: Expression, args: Vec<Expression>) -> Statement {
        FunctionCall {
            id: NodeId::sentinel(),
            subject: Box::new(subject),
            args,
        }
        .wrap_in_statement()
    }

    fn t_i32() -> TypeSpecifier {
        TypeSpecifier::Integer {
            width: 32,
            signed: true,
        }
    }
    fn t_unit() -> TypeSpecifier {
        TypeSpecifier::Unit
    }
    fn t_f64() -> TypeSpecifier {
        TypeSpecifier::Float { width: 64 }
    }
    fn t_ptr(inner: TypeSpecifier) -> TypeSpecifier {
        TypeSpecifier::Pointer(Box::new(inner))
    }

    // ---- roundtrip test infrastructure ---------------------------------------

    /// Build a module, pretty-print it, parse the output, then verify:
    /// 1. Structural equality (ignoring `NodeId`).
    /// 2. Pretty-print idempotency (re-printing the parsed AST
    ///    produces identical text).
    fn roundtrip(ast: Module) {
        let printed = ast.indent_print(0);
        eprintln!("=== PRINTED ===\n{}", printed);
        let parsed = parse_module(&printed);
        assert!(
            ast.eq_ignore_id(&parsed),
            "Round-trip structural equality failed"
        );
        let reparsed = parsed.indent_print(0);
        assert_eq!(printed, reparsed, "Pretty-print idempotency failed");
    }

    // ---- tests ---------------------------------------------------------------

    #[test]
    fn empty_module() {
        roundtrip(module_(vec![]));
    }

    #[test]
    fn module_with_imports_exports() {
        roundtrip(Module {
            id: NodeId::sentinel(),
            imports: vec!["std.io".into(), "std.math".into()],
            exports: vec!["main".into()],
            global_vars: vec![],
            functions: vec![],
            struct_definitions: vec![],
        });
    }

    #[test]
    fn simple_function() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_i32(),
            block(vec![stmt_ret(expr_int(42))], expr_unit()),
        )]));
    }

    #[test]
    fn function_with_params() {
        roundtrip(module_(vec![function(
            "add",
            vec![param("a", t_i32()), param("b", t_i32())],
            t_i32(),
            block(
                vec![],
                expr_binop(BinOp::Add, expr_ident("a"), expr_ident("b")),
            ),
        )]));
    }

    #[test]
    fn function_call_expr() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_unit(),
            block(
                vec![],
                expr_call(expr_ident("foo"), vec![expr_int(1), expr_float(2.5)]),
            ),
        )]));
    }

    #[test]
    fn if_then_else() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_i32(),
            block(
                vec![],
                IfThenElse::if_else_block(expr_ident("cond"), expr_int(1), expr_int(0))
                    .wrap_in_expression(),
            ),
        )]));
    }

    #[test]
    fn packed_initialization() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_unit(),
            block(
                vec![stmt_init_packed(PackedInitialization::untyped(
                    AssignmentPattern::Tuple(vec![
                        AssignmentPattern::Identifier("a".into()),
                        AssignmentPattern::Identifier("b".into()),
                    ]),
                    expr_call(expr_ident("f"), vec![]),
                ))],
                expr_unit(),
            ),
        )]));
    }

    #[test]
    fn unop_and_member_access() {
        roundtrip(module_(vec![function(
            "test",
            vec![],
            t_i32(),
            block(vec![], expr_member(expr_ident("point"), "x")),
        )]));
    }

    #[test]
    fn float_type() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_f64(),
            block(vec![], expr_float(3.14)),
        )]));
    }

    #[test]
    fn block_tail_stmt() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_unit(),
            block(vec![stmt_tail(expr_int(99))], expr_unit()),
        )]));
    }

    #[test]
    fn parse_example_from_readme() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_i32(),
            block(vec![stmt_ret(expr_int(42))], expr_unit()),
        )]));
    }

    #[test]
    fn function_call_stmt() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_unit(),
            block(
                vec![call_stmt(expr_ident("println"), vec![expr_ident("msg")])],
                expr_unit(),
            ),
        )]));
    }

    #[test]
    fn pointer_type() {
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_ptr(TypeSpecifier::NonScalar("Int".into())),
            block(vec![], expr_unit()),
        )]));
    }

    #[test]
    fn nested_block() {
        let inner = block(vec![stmt_ret(expr_int(1))], expr_unit());
        roundtrip(module_(vec![function(
            "main",
            vec![],
            t_unit(),
            block(vec![stmt_block(inner)], expr_unit()),
        )]));
    }

    #[test]
    fn parse_bare_expression() {
        let expr = parse_expression("lit_int(42)\n");
        assert!(matches!(expr.kind, ExpressionKind::IntegerLiteral(42)));
    }

    #[test]
    fn parse_bare_block() {
        let block = parse_block("block\n  - return\n    lit_int(1)\n  @unit\n");
        assert_eq!(block.statements.len(), 1);
        assert!(matches!(block.last.kind, ExpressionKind::Unit));
    }

    #[test]
    fn parse_bare_statement() {
        let stmt = parse_statement("- return\n  lit_int(42)\n");
        assert!(matches!(stmt.kind, StatementKind::Return(_)));
    }
}
