[package]
name = "zea-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.zea-ipr]
path = "../zea-ipr"

[dependencies.arbitrary]
version = "1"
features = ["derive"]

[[bin]]
name = "label_ast_nodes"
path = "fuzz_targets/label_ast_nodes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "scope_idents"
path = "fuzz_targets/scope_idents.rs"
test = false
doc = false
bench = false
