[package]
name = "zea-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
zea-ast = { path = "../zea-ast" }
lalrpop-util = { version = "0.23.1", features = ["lexer", "unicode"], optional = true }
log = "0.4.31"

[build-dependencies]
lalrpop = { version = "0.23.1", optional = true }


[features]
lalrpop_parser = ["dep:lalrpop", "dep:lalrpop-util"]
zepast = ["zea-ast/visualisation"]
default = ["lalrpop_parser"]


[lib]
doctest = false