use std::str::FromStr;
use zea_ipr::ast::ipr::*;
use zea_ipr::ast::{BinOp, UnOp, NodeId};
use crate::{IPRModuleItem, separate_module_items};

grammar<'ast>;

Comma0<T>: Vec<T> = {
    => vec![],
    <first:T> <items:("," <T>)*> => {
        let mut first = vec![first];
        first.extend(items);
        first
    }
};

Comma1<T>: Vec<T> = {
    <first:T> <rest:("," <T>)*>  => {
        let mut items = vec![first];
        items.extend(rest);
        items
    }
};

TTypedIdent:IPRTypedIdentifier = {
    <i:ExprIdent> ":" <t:TType> =>IPRTypedIdentifier::new(t, i)
};

pub Mod: IPRModule = {
    <name:ModName> <imports:ModImports?> <exports:ModExports?> <(global_vars, functions, struct_definitions, tagged_unions):ModSymbols> => {
        IPRModule {
            attributes: Default::default(),
            id: NodeId::sentinel(),
            name,
            imports: imports.unwrap_or(vec![]),
            exports: exports.unwrap_or(vec![]),
            global_vars,
            functions,
            struct_definitions
        }
 }
};

Attr: (String,Option<String>) = {
    "@" <key:ExprIdent> => (key,None),
    "@" <key:ExprIdent> "=" <value:ExprIdent> => (key,Some(value))
};

AttrList: Vec<(String,Option<String>)> = {
    Attr => vec![<>],
    <head:Attr> <tail:AttrList> => {
        let mut tail = tail;
        tail.push(head);
        tail
    }
}


CondBranch: IPRBranch = {
    "if" <condition:Expr> <true_case:Block> => {
        IPRBranch::if_block(condition, true_case.wrap_in_expression())
    },
    "if" <condition:Expr> <true_case:Block> "else" <false_case:Block> =>
        IPRBranch::if_else_block(condition, true_case.wrap_in_expression(), false_case.wrap_in_expression())
};

ModName: String = {
    "module" <name:ExprIdent> => name
};

ModImports: Vec<String> = {
    "imports" "{" <imps:Comma0<ExprIdent>> "}" => imps
};

ModExports: Vec<String> = {
    "exports"  "{" <imps:Comma0<ExprIdent>>  "}"=> imps
};
#[inline]
ModSymbols: (
Vec<IPRInitializationBlock>,
Vec<IPRFunction>,
Vec<IPRStructDataTypeDefinition>,
Vec<IPRTaggedUnionDataTypeDefinition>
) = {
    ModSymbolsHelper => separate_module_items(<>)
};

ModSymbolsHelper: Vec<IPRModuleItem> = {
    => vec![],
    <cur: Init> <rest:ModSymbolsHelper> => {
        let mut v = Vec::with_capacity(rest.len() + 1);
        v.push(IPRModuleItem::Init(cur));
        v.extend(rest);
        v
    },
    <cur: Func> <rest:ModSymbolsHelper> => {
        let mut v = Vec::with_capacity(rest.len() + 1);
        v.push(IPRModuleItem::Func(cur));
        v.extend(rest);
        v
        },

   // <cur: StructDef> <rest:ModSymbolsHelper> => {
   //             let mut v = rest;
   //                     v.push(IPRModuleItem::StructDef(cur));
   //                     v
   //         },

};

// pub StructDef: IPRStructDataTypeDefinition = {
//    "struct" <name:TypeIdent> "{" <members:Comma0<TTypedIdent>> "}" => {
//        IPRStructDataTypeDefinition {
//            id: NodeId::sentinel(),
//            name,
//            members: vec![],
//            reorder_fields: None,
//            alignment: None
//        }
// },
//};

Init: IPRInitializationBlock = {
    <p:AssignPat> ":" "=" <val:Expr> ";" => {
    IPRInitializationBlock::packed (
        None,
        p,
        val
    )
 },
    <p:AssignPat> ":" <typ:TType> "=" <val:Expr> ";" => {
    IPRInitializationBlock::packed (
            Some(typ),
            p,
            val
        )
 },
}
AssignPat: IPRAssignmentPattern = {
    <i:ExprIdent> => IPRAssignmentPattern::Identifier(i),
    "`" <AssignPatInner>
}

#[inline]
AssignPatInner: IPRAssignmentPattern = {
    <i:ExprIdent> => IPRAssignmentPattern::Identifier(i),
    "(" <pats:Comma1<AssignPatInner>> ")" => IPRAssignmentPattern::Tuple(pats)
}

Reassign: IPRReassignment = {
    <i:ExprIdent> "=" <v:Expr> ";" => {
        IPRReassignment {
            id: NodeId::sentinel(),
            assignee: i,
            value: v
        }
 }
};
FuncCall: IPRFunctionCall = {
    <subject:ExprIdent> "(" <args:Comma0<Expr>> ")" => {
        IPRFunctionCall {
            id: NodeId::sentinel(),
            subject: Box::new(IPRExpression::wrap_ident(subject)),
            args
        }
    }
};


Func: IPRFunction = {
    "fn" <name:ExprIdent>
    "(" <args:Comma0<TTypedIdent>> ")"
    <body:Block> => {
        let params: Vec<IPRFuncParam> = args.into_iter().map(IPRFuncParam::from).collect();
        IPRFunction {
            attributes: Default::default(),
            id: NodeId::sentinel(),
            name,
            params,
            returns: IPRTypeSpecifier::Unit,
            body
        }
    },
    "fn" <name:ExprIdent>
    "(" <args:Comma0<TTypedIdent>> ")"
    "->" <funcreturns:TType> <body:Block> => {
        let params: Vec<IPRFuncParam> = args.into_iter().map(IPRFuncParam::from).collect();
        IPRFunction {
            attributes: Default::default(),
            id: NodeId::sentinel(),
            name,
            params,
            returns: funcreturns,
            body
        }
    }
};
TType:IPRTypeSpecifier = {
   TypeIdent => {IPRTypeSpecifier::inner_from_str(&<>)},
    <t:TType> "*" => {IPRTypeSpecifier::Pointer(Box::new(t))},
    "[" <t:TType> "]" => {IPRTypeSpecifier::ArrayOf(Box::new(t))},
};

Block: IPRBlockExpression = {
    "{" <statements:(<Stmt>)*> <tail:Expr?> "}" => {
        let tail = if let Some(tail) = tail {
            tail
        } else {
            IPRExpression::unit()
        };
        IPRBlockExpression {
            attributes: Default::default(),
            id: NodeId::sentinel(),
            statements,
            tail
        }
    },
};

Stmt: IPRStatement = {
    "return" <e:Expr> ";" => {
        IPRStatement {
            id: NodeId::sentinel(),
            kind: IPRStatementKind::Return(e)
        }
    },
    <init:Init> => IPRStatement {
        id: NodeId::sentinel(),
        kind: IPRStatementKind::Initialization(init)
    },
    <reinit:Reassign> => reinit.wrap_in_statement(),
    <block:Block> ";" => block.wrap_in_statement(),
    <call:FuncCall> ";" => call.wrap_in_statement(),
    <branch:CondBranch> ";" => branch.wrap_in_statement()
};

pub Expr: IPRExpression = ExprBranch;

ExprBranch: IPRExpression = {
    <b:CondBranch> => b.wrap_in_expression(),
    ExprOr,
     <b:Block> => b.wrap_in_expression(),
};

ExprOr: IPRExpression = {
    <l:ExprXor> "||" <r:ExprOr>  => IPRExpression::binop(BinOp::LogOr, l, r),
    ExprXor,
};
ExprXor: IPRExpression = {
    <l:ExprAnd> "^^" <r:ExprXor> => IPRExpression::binop(BinOp::LogXor, l, r),
    ExprAnd,
};
ExprAnd: IPRExpression = {
    <l:ExprBit> "&&" <r:ExprAnd> => IPRExpression::binop(BinOp::LogAnd, l, r),
    ExprBit,
};
ExprBit: IPRExpression = {
     <l:ExprEq> "|" <r:ExprBit> => IPRExpression::binop(BinOp::BitOr, l, r),
    <l:ExprEq> "^" <r:ExprBit> => IPRExpression::binop(BinOp::BitXor, l, r),
    <l:ExprEq> "&" <r:ExprBit> => IPRExpression::binop(BinOp::BitAnd, l, r),
    ExprEq,
};
ExprEq: IPRExpression = {
    <l:ExprCmp> "==" <r:ExprEq> => IPRExpression::binop(BinOp::Eq, l, r),
    <l:ExprCmp> "!=" <r:ExprEq> => IPRExpression::binop(BinOp::Neq, l, r),
    ExprCmp,
};
ExprCmp: IPRExpression = {
    <l:ExprShift> "<" <r:ExprCmp> => IPRExpression::binop(BinOp::LT, l, r),
    <l:ExprShift> ">" <r:ExprCmp>  => IPRExpression::binop(BinOp::GT, l, r),
    <l:ExprShift> "<=" <r:ExprCmp>  => IPRExpression::binop(BinOp::Leq, l, r),
    <l:ExprShift> ">=" <r:ExprCmp>  => IPRExpression::binop(BinOp::Geq, l, r),
    ExprShift,
};
ExprShift: IPRExpression = {
    <l:ExprAdd> "<<" <r:ExprShift>  => IPRExpression::binop(BinOp::Lsh, l, r),
    <l:ExprAdd> ">>" <r:ExprShift> => IPRExpression::binop(BinOp::Rsh, l, r),
    ExprAdd,
};
ExprAdd: IPRExpression = {
    <l:ExprMul> "+" <r:ExprAdd>  => IPRExpression::binop(BinOp::Add, l, r),
    <l:ExprMul> "-" <r:ExprAdd> => IPRExpression::binop(BinOp::Sub, l, r),
    ExprMul,
};
ExprMul: IPRExpression = {
      <l:ExprMul> "*" <r:ExprUnary> => IPRExpression::binop(BinOp::Mul, l, r),
     <l:ExprMul> "/" <r:ExprUnary> => IPRExpression::binop(BinOp::Div, l, r),
     <l:ExprMul> "%" <r:ExprUnary>  => IPRExpression::binop(BinOp::Mod, l, r),
    ExprUnary,
};
ExprUnary: IPRExpression = {
    "!" <e:ExprUnary> => IPRExpression::unop(UnOp::LogNot, e),
    "~" <e:ExprUnary> => IPRExpression::unop(UnOp::BitNot, e),
    "-" <e:ExprUnary> => IPRExpression::unop(UnOp::Neg, e),
    ExprCall,
};
ExprCall: IPRExpression = {
    <c:FuncCall> => c.wrap_in_expression(),
    ExprPostfix
}

ExprPostfix: IPRExpression = {
    <t:ExprPostfix> "." <m:ExprIdent> => IPRExpression::member_access(t,m),
    <t:ExprPostfix> "[" <i:Expr> "]" => IPRExpression::binop(BinOp::Subscript, t, i),
    ExprAtom
};


ExprAtom: IPRExpression = {
    <n:Num>       => IPRExpression::wrap_lit_int(n),
    <s:ExprIdent> => IPRExpression::wrap_ident(s),
    "(" <Expr> ")",
};

Num: usize = {
    r"[0-9_]+" => usize::from_str(&<>.replace("_", "")).unwrap(),
    r"0x[0-9a-fA-F_]+" => usize::from_str_radix(&<>[2..].replace("_", ""), 16).unwrap(),
    r"0b[01_]+" => usize::from_str_radix(&<>[2..].replace("_", ""), 2).unwrap(),
};
TypeIdent: String = {r"[A-Z][a-zA-Z_0-9]*" => String::from(<>)}
ExprIdent: String = {r"[a-z][a-z0-9-]*[?!]*" => String::from(<>)}
