use std::str::FromStr;
use zea_ast::zea::hir_nodes::*;
use zea_ast::zea::{BinOp, UnOp, NodeId};
use crate::{HIRModuleItem, separate_module_items};

grammar<'ast>;

Comma0<T>: Vec<T> = {
    <items:(<T> ",")*> <last:T?> => {
        let mut items = items;
        items.extend(last);
        items
    }
};
Comma0NoTrail<T>: Vec<T> = {
    <first:T> <items:(","<T> )*> => {
        let mut first = vec![first];
        first.extend(items);
        first
    }
};

Comma1<T>: Vec<T> = {
    <first:T> <rest:("," <T>)*> ","? => {
        let mut items = vec![first];
        items.extend(rest);
        items
    }
};

TTypedIdent:HIRTypedIdentifier = {
    <i:ExprIdent> ":" <t:TType> =>HIRTypedIdentifier::new(t, i)
};

pub Mod: HIRModule = {
    <name:ModName> <imports:ModImports?> <exports:ModExports?> <(global_vars, functions, struct_definitions, tagged_unions):ModSymbols> => {
        HIRModule {
            id: NodeId::sentinel(),
            imports: imports.unwrap_or(vec![]),
            exports: exports.unwrap_or(vec![]),
            global_vars,
            functions,
            struct_definitions
        }
 }
};

CondBranch: HIRBranch = {
    "if" <condition:Expr> <true_case:Block> => {
        HIRBranch::if_block(condition, true_case.wrap_in_expression())
    },
    "if" <condition:Expr> <true_case:Block> "else" <false_case:Block> =>
        HIRBranch::if_else_block(condition, true_case.wrap_in_expression(), false_case.wrap_in_expression())
};

ModName: String = {
    "module" <name:ExprIdent> => name
};

ModImports: Vec<String> = {
    "imports" "{" <imps:Comma0<ExprIdent>> "}" => imps
};

ModExports: Vec<String> = {
    "exports"  "{" <imps:Comma0<ExprIdent>>  "}"=> imps
};
#[inline]
ModSymbols: (
Vec<HIRInitializationBlock>,
Vec<HIRFunction>,
Vec<HIRStructDataTypeDefinition>,
Vec<HIRTaggedUnionDataTypeDefinition>
) = {
    ModSymbolsHelper => separate_module_items(<>)
};

ModSymbolsHelper: Vec<HIRModuleItem> = {
    => vec![],
    <cur: Init> <rest:ModSymbolsHelper> => {
        let mut v = rest;
        v.push(HIRModuleItem::Init(cur));
        v
    },
    <cur: Func> <rest:ModSymbolsHelper> => {
            let mut v = rest;
                    v.push(HIRModuleItem::Func(cur));
                    v
        },

   // <cur: StructDef> <rest:ModSymbolsHelper> => {
   //             let mut v = rest;
   //                     v.push(HIRModuleItem::StructDef(cur));
   //                     v
   //         },

};

// pub StructDef: HIRStructDataTypeDefinition = {
//    "struct" <name:TypeIdent> "{" <members:Comma0<TTypedIdent>> "}" => {
//        HIRStructDataTypeDefinition {
//            id: NodeId::sentinel(),
//            name,
//            members: vec![],
//            reorder_fields: None,
//            alignment: None
//        }
// },
//};

pub Init: HIRInitializationBlock = {
    <p:AssignPat> ":" "=" <val:Expr> ";" => {
    HIRInitializationBlock::packed (
        None,
        p,
        val
    )
 },
    <p:AssignPat> ":" <typ:TType> "=" <val:Expr> ";" => {
    HIRInitializationBlock::packed (
            Some(typ),
            p,
            val
        )
 },
}
pub AssignPat: HIRAssignmentPattern = {
    <i:ExprIdent> => HIRAssignmentPattern::Identifier(i),
    "@" <AssignPatInner>
}

#[inline]
AssignPatInner: HIRAssignmentPattern = {
    <i:ExprIdent> => HIRAssignmentPattern::Identifier(i),
    "(" <pats:Comma1<AssignPatInner>> ")" => HIRAssignmentPattern::Tuple(pats)
}

pub Reassign: HIRReassignment = {
    <i:ExprIdent> "=" <v:Expr> ";" => {
        HIRReassignment {
            id: NodeId::sentinel(),
            assignee: i,
            value: v
        }
 }
};
pub FuncCall: HIRFunctionCall = {
    <subject:ExprIdent> "(" <args:Comma0<Expr>> ")" => {
        HIRFunctionCall {
            id: NodeId::sentinel(),
            subject: Box::new(HIRExpression::wrap_ident(subject)),
            args
        }
    }
};


pub Func: HIRFunction = {
    "fn" <name:ExprIdent>
    "(" <args:Comma0<TTypedIdent>> ")"
    <body:Block> => {
        let params: Vec<HIRFuncParam> = args.into_iter().map(HIRFuncParam::from).collect();
        HIRFunction {
            id: NodeId::sentinel(),
            name,
            params,
            returns: HIRTypeSpecifier::NonScalar("Void".to_string()),
            body
        }
    },
    "fn" <name:ExprIdent>
    "(" <args:Comma0<TTypedIdent>> ")"
    "->" <funcreturns:TType> <body:Block> => {
        let params: Vec<HIRFuncParam> = args.into_iter().map(HIRFuncParam::from).collect();
        HIRFunction {
            id: NodeId::sentinel(),
            name,
            params,
            returns: funcreturns,
            body
        }
    }
};
TType:HIRTypeSpecifier = {
   TypeIdent => {HIRTypeSpecifier::NonScalar(<>)},
    <t:TType> "*" => {HIRTypeSpecifier::Pointer(Box::new(t))},
    "[" <t:TType> "]" => {HIRTypeSpecifier::ArrayOf(Box::new(t))},
};

Block: HIRBlockExpression = {
    "{" <statements:(<Stmt>)*> <tail:Expr?> "}" => {
        let last = if let Some(tail) = tail {
            tail
        } else {
            HIRExpression::unit()
        };
        HIRBlockExpression {
            id: NodeId::sentinel(),
            statements,
            last
        }
    },
};
FuncBody: HIRBlockExpression = {
    "{" <statements:(<Stmt>)*> <tail:Expr?> "}" => {
        let last = if let Some(tail) = tail {
            tail
        } else {
            HIRExpression::unit()
        };
        HIRBlockExpression {
            id: NodeId::sentinel(),
            statements,
            last
        }
    },
};

pub Stmt: HIRStatement = {
    "return" <e:Expr> ";" => {
        HIRStatement {
            id: NodeId::sentinel(),
            kind: HIRStatementKind::Return(e)
        }
    },
    <init:Init> => HIRStatement {
        id: NodeId::sentinel(),
        kind: HIRStatementKind::Initialization(init)
    },
    <reinit:Reassign> => reinit.wrap_in_statement(),
    <block:Block> => block.wrap_in_statement(),
    <call:FuncCall> ";" => call.wrap_in_statement(),
    <branch:CondBranch> ";" => branch.wrap_in_statement()
};

pub Expr: HIRExpression = ExprBranch;

ExprBranch: HIRExpression = {
    <b:CondBranch> => b.wrap_in_expression(),
    ExprOr
};

ExprOr: HIRExpression = {
    <l:ExprXor> "||" <r:ExprOr>  => HIRExpression::binop(BinOp::LogOr, l, r),
    ExprXor,
};
ExprXor: HIRExpression = {
    <l:ExprAnd> "^^" <r:ExprXor> => HIRExpression::binop(BinOp::LogXor, l, r),
    ExprAnd,
};
ExprAnd: HIRExpression = {
    <l:ExprBit> "&&" <r:ExprAnd> => HIRExpression::binop(BinOp::LogAnd, l, r),
    ExprBit,
};
ExprBit: HIRExpression = {
     <l:ExprEq> "|" <r:ExprBit> => HIRExpression::binop(BinOp::BitOr, l, r),
    <l:ExprEq> "^" <r:ExprBit> => HIRExpression::binop(BinOp::BitXor, l, r),
    <l:ExprEq> "&" <r:ExprBit> => HIRExpression::binop(BinOp::BitAnd, l, r),
    ExprEq,
};
ExprEq: HIRExpression = {
    <l:ExprCmp> "==" <r:ExprEq> => HIRExpression::binop(BinOp::Eq, l, r),
    <l:ExprCmp> "!=" <r:ExprEq> => HIRExpression::binop(BinOp::Neq, l, r),
    ExprCmp,
};
ExprCmp: HIRExpression = {
    <l:ExprShift> "<" <r:ExprCmp> => HIRExpression::binop(BinOp::LT, l, r),
    <l:ExprShift> ">" <r:ExprCmp>  => HIRExpression::binop(BinOp::GT, l, r),
    <l:ExprShift> "<=" <r:ExprCmp>  => HIRExpression::binop(BinOp::Leq, l, r),
    <l:ExprShift> ">=" <r:ExprCmp>  => HIRExpression::binop(BinOp::Geq, l, r),
    ExprShift,
};
ExprShift: HIRExpression = {
    <l:ExprAdd> "<<" <r:ExprShift>  => HIRExpression::binop(BinOp::Lsh, l, r),
    <l:ExprAdd> ">>" <r:ExprShift> => HIRExpression::binop(BinOp::Rsh, l, r),
    ExprAdd,
};
ExprAdd: HIRExpression = {
    <l:ExprMul> "+" <r:ExprAdd>  => HIRExpression::binop(BinOp::Add, l, r),
    <l:ExprMul> "-" <r:ExprAdd> => HIRExpression::binop(BinOp::Sub, l, r),
    ExprMul,
};
ExprMul: HIRExpression = {
      <l:ExprMul> "*" <r:ExprUnary> => HIRExpression::binop(BinOp::Mul, l, r),
     <l:ExprMul> "/" <r:ExprUnary> => HIRExpression::binop(BinOp::Div, l, r),
     <l:ExprMul> "%" <r:ExprUnary>  => HIRExpression::binop(BinOp::Mod, l, r),
    ExprUnary,
};
ExprUnary: HIRExpression = {
    "!" <e:ExprUnary> => HIRExpression::unop(UnOp::LogNot, e),
    "~" <e:ExprUnary> => HIRExpression::unop(UnOp::BitNot, e),
    "-" <e:ExprUnary> => HIRExpression::unop(UnOp::Neg, e),
    ExprCall,
};
ExprCall: HIRExpression = {
    <c:FuncCall> => c.wrap_in_expression(),
    ExprPostfix
}

ExprPostfix: HIRExpression = {
    <t:ExprPostfix> "." <m:ExprIdent> => HIRExpression::member_access(t,m),
    <t:ExprPostfix> "[" <i:Expr> "]" => HIRExpression::binop(BinOp::Subscript, t, i),
    ExprAtom
};


ExprAtom: HIRExpression = {
    <n:Num>       => HIRExpression::wrap_lit_int(n),
    <s:ExprIdent> => HIRExpression::wrap_ident(s),
    "(" <Expr> ")"
};

Num: usize = {
    r"[0-9_]+" => usize::from_str(&<>.replace("_", "")).unwrap(),
    r"0x[0-9a-fA-F_]+" => usize::from_str_radix(&<>[2..].replace("_", ""), 16).unwrap(),
    r"0b[01_]+" => usize::from_str_radix(&<>[2..].replace("_", ""), 2).unwrap(),
};
TypeIdent: String = {r"[A-Z][a-zA-Z_0-9]*" => String::from(<>)}
ExprIdent: String = {r"[a-z][a-z0-9-]*[?!]*" => String::from(<>)}
