//! This crate holds the AST definition for the Zea language, along with the target C AST.
use std::{fmt::Debug, hash::Hash, marker::PhantomData};

use indexmap::{
    IndexSet,
    set::{Iter, MutableValues},
};
/// The AST's for the ZEA language
pub mod ast;
mod typecheck;
pub use typecheck::typecheck_module;
mod impls;
pub mod visualisation;

pub trait ZeaError<'m> {
    type ErrContext;
    fn zea_error_format(&'m self, ctx: &'m Self::ErrContext) -> String;
}

/// An interning table generic over its key and value.
/// A key is commonly a Newtype for some integer type, i.e. a `struct SomeID(usize);`
/// Care must to taken to only use keys that are generated by the `.intern()` method of the corresponding table,
/// as it guarantees non-panicking access.
#[derive(PartialEq, Eq, Clone)]
pub struct InternTable<Key: From<usize> + Into<usize>, Value: Hash + Eq> {
    set: IndexSet<Value>,
    _phantom: PhantomData<Key>,
}

impl<Key: From<usize> + Into<usize> + Debug, Value: Hash + Eq + Debug> Debug
    for InternTable<Key, Value>
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("InternTable")
            .field("set", &self.set)
            .finish()
    }
}

impl<Key: From<usize> + Into<usize>, Value: Hash + Eq> InternTable<Key, Value> {
    pub fn new() -> Self {
        Self {
            set: IndexSet::new(),
            _phantom: PhantomData,
        }
    }
    pub fn intern(&mut self, item: Value) -> Key {
        let (idx, _) = self.set.insert_full(item);
        idx.into()
    }
    pub fn get_by_id(&self, id: Key) -> Option<&Value> {
        self.set.get_index(id.into())
    }
    pub fn get_unchecked(&self, item: &Value) -> Key {
        self.set
            .get_index_of(item)
            .expect("non-interned item in intern table")
            .into()
    }
    pub fn iter(&self) -> Iter<'_, Value> {
        self.set.iter()
    }

    fn get_mut_by_id(&mut self, id: Key) -> Option<&mut Value> {
        self.set.get_index_mut2(id.into())
    }
}
impl<Key: From<usize> + Into<usize>, Value: Hash + Eq> Default for InternTable<Key, Value> {
    fn default() -> Self {
        Self::new()
    }
}
/// Supply a struct's Name to Implement the NodeLabeler trait for it.
/// This macro requires the struct to have a `label: usize` field.
///
/// Additionaly a lebel suffix mat be provided to customize
/// [`NodeLabeler::next_label_with_ident_string`]
macro_rules! impl_nodelabeler {
    ($typ:ident, $label:literal) => {
        impl NodeLabeler for $typ {
            fn labeler_from(mut other_generator: impl NodeLabeler) -> Self {
                Self {
                    label: other_generator.next_id().0,
                }
            }
            fn next_id(&mut self) -> NodeId {
                let label = self.label;
                self.label += 1;
                NodeId(label)
            }
            fn next_label_with_ident_string(&mut self) -> (NodeId, String) {
                let label = self.next_id();
                (label, format!(concat!("__", $label, "{}"), label))
            }
        }
    };
    ($typ:ident) => {
        impl NodeLabeler for $typ {
            fn labeler_from(mut other_generator: impl NodeLabeler) -> Self {
                Self {
                    label: other_generator.next_id().0,
                }
            }
            fn next_id(&mut self) -> NodeId {
                let label = self.label;
                self.label += 1;
                NodeId(label)
            }
            fn next_label_with_ident_string(&mut self) -> (NodeId, String) {
                let label = self.next_id();
                (label, format!("__synthetic{}", label))
            }
        }
    };
}
pub(crate) use impl_nodelabeler;

pub mod attributes {
    //! This module contains compiler directives and annotations for language items
    //! Some Language items like structs, functions, modules etc.
    //! Have a set of default attributes,
    //! Like if they should be a candidate for dead code elimination,
    //! if a function is hot or cold, etc.
    //!
    //! Zea Attributes in some cases cascade into children items.
    //! As such, deriving the attributes for some item goes as follows:
    //! - start with the default attributes for this item
    //! - inherit applicable attributes from the parent item
    //! - modify any attributes that where specified using supplied directives.
    //!
    //! For some items you may see some attributes prefixed with `cascade_`,
    //! this means that the item itself does not use that attribute,
    //! but solely lets its children items inherit from it.
    #![allow(unused)]
    use arbitrary::Arbitrary;
    pub trait AttrListLike: Default {
        fn from_attr_list(list: Vec<ZeaAttribute>) -> Self {
            let mut s = Self::default();
            s.update_from_attr_list(list);
            s
        }
        fn update_from_attr_list(&mut self, list: Vec<ZeaAttribute>);
        fn as_attr_list(&self) -> Vec<ZeaAttribute>;
    }
    #[derive(Debug, Clone, Arbitrary)]
    pub struct IPRModuleAttributes {
        /// Should chid items be applicable for dead code elimination?
        cascade_keep: KeepAttribute,
    }

    impl Default for IPRModuleAttributes {
        fn default() -> Self {
            Self {
                cascade_keep: KeepAttribute::EliminateUnused,
            }
        }
    }
    impl AttrListLike for IPRModuleAttributes {
        fn update_from_attr_list(&mut self, list: Vec<ZeaAttribute>) {
            for attr in list {
                if let ZeaAttribute::Keep(keep) = attr {
                    self.cascade_keep = keep;
                    return;
                }
            }
        }
        fn as_attr_list(&self) -> Vec<ZeaAttribute> {
            vec![ZeaAttribute::Keep(self.cascade_keep)]
        }
    }

    #[derive(Debug, Clone, Arbitrary)]
    pub struct IPRStructAttributes {
        /// How should the fields of this struct be ordered?
        field_order: FieldOrderAttribute,
        alignment: AlignmentAttribute,
        keep: KeepAttribute,
    }

    impl Default for IPRStructAttributes {
        fn default() -> Self {
            Self {
                field_order: Default::default(),
                alignment: Default::default(),
                keep: KeepAttribute::Keep,
            }
        }
    }
    impl AttrListLike for IPRStructAttributes {
        fn update_from_attr_list(&mut self, list: Vec<ZeaAttribute>) {
            for attr in list {
                match attr {
                    ZeaAttribute::Align(type_alignment) => {
                        self.alignment = type_alignment;
                    }
                    ZeaAttribute::Ordering(struct_field_ordering) => {
                        self.field_order = struct_field_ordering;
                    }
                    ZeaAttribute::Keep(keep) => {
                        self.keep = keep;
                    }
                    _ => {}
                }
            }
        }
        fn as_attr_list(&self) -> Vec<ZeaAttribute> {
            vec![
                ZeaAttribute::Ordering(self.field_order),
                ZeaAttribute::Align(self.alignment),
                ZeaAttribute::Keep(self.keep),
            ]
        }
    }
    #[derive(Debug, Copy, Clone, Arbitrary)]
    pub struct IPRFunctionAttributes {
        /// should this function be inlined?
        inline: InlineAttribute,
        /// is this function called often?
        temperature: TemperatureAttribute,
        /// Should dead code elimination
        /// be performed on this function?
        keep: KeepAttribute,
        /// Must the caller use the return value?
        must_use: MustUseAttribute,
    }

    impl Default for IPRFunctionAttributes {
        fn default() -> Self {
            Self {
                inline: InlineAttribute::AsNecessary,
                temperature: TemperatureAttribute::LukeWarm,
                keep: KeepAttribute::Keep,
                must_use: MustUseAttribute::MayDiscard,
            }
        }
    }
    impl AttrListLike for IPRFunctionAttributes {
        fn update_from_attr_list(&mut self, list: Vec<ZeaAttribute>) {
            for attr in list {
                match attr {
                    ZeaAttribute::Inline(inline_attribute) => {
                        self.inline = inline_attribute;
                    }
                    ZeaAttribute::Temperature(temperature_attribute) => {
                        self.temperature = temperature_attribute;
                    }
                    ZeaAttribute::MustUse(must_use_attribute) => {
                        self.must_use = must_use_attribute;
                    }
                    ZeaAttribute::Keep(keep_attribute) => {
                        self.keep = keep_attribute;
                    }
                    _ => {}
                }
            }
        }
        fn as_attr_list(&self) -> Vec<ZeaAttribute> {
            vec![
                ZeaAttribute::Inline(self.inline),
                ZeaAttribute::Temperature(self.temperature),
                ZeaAttribute::Keep(self.keep),
                ZeaAttribute::MustUse(self.must_use),
            ]
        }
    }

    #[derive(Default, Debug, Copy, Clone, Arbitrary, PartialEq, Eq)]
    pub struct IPRBlockAttributes {
        temperature: TemperatureAttribute,
    }
    impl AttrListLike for IPRBlockAttributes {
        fn update_from_attr_list(&mut self, list: Vec<ZeaAttribute>) {
            for attr in list {
                if let ZeaAttribute::Temperature(t) = attr {
                    self.temperature = t;
                    return;
                }
            }
        }
        fn as_attr_list(&self) -> Vec<ZeaAttribute> {
            vec![ZeaAttribute::Temperature(self.temperature)]
        }
    }
    #[derive(Default, Debug, Copy, Clone, Arbitrary, PartialEq, Eq)]
    pub struct IPRBranchAttributes {
        taken_path_temperature: TemperatureAttribute,
    }

    impl IPRBranchAttributes {
        pub fn then_path_temperature(&self) -> TemperatureAttribute {
            self.taken_path_temperature
        }
        pub fn else_path_temperature(&self) -> TemperatureAttribute {
            match self.taken_path_temperature {
                TemperatureAttribute::Hot => TemperatureAttribute::Cold,
                TemperatureAttribute::Cold => TemperatureAttribute::Hot,
                TemperatureAttribute::LukeWarm => TemperatureAttribute::LukeWarm,
            }
        }
    }
    impl AttrListLike for IPRBranchAttributes {
        fn update_from_attr_list(&mut self, list: Vec<ZeaAttribute>) {
            for attr in list {
                if let ZeaAttribute::Temperature(t) = attr {
                    self.taken_path_temperature = t;
                    return;
                }
            }
        }
        fn as_attr_list(&self) -> Vec<ZeaAttribute> {
            vec![ZeaAttribute::Temperature(self.taken_path_temperature)]
        }
    }

    #[derive(Debug, Copy, Clone, Arbitrary, PartialEq, Eq, Default)]
    pub enum TemperatureAttribute {
        Hot,
        Cold,
        #[default]
        LukeWarm,
    }

    #[derive(Debug, Copy, Clone, Arbitrary, PartialEq, Eq, Default)]
    pub enum FieldOrderAttribute {
        #[default]
        ReprC,
        Descending,
    }
    #[derive(Debug, Copy, Clone, Arbitrary, PartialEq, Eq, Default)]
    pub enum AlignmentAttribute {
        #[default]
        Inferred,
        Explicit(usize),
    }

    #[derive(Debug, Copy, Clone, Arbitrary, PartialEq, Eq, Default)]
    pub enum InlineAttribute {
        Always,
        #[default]
        AsNecessary,
        Never,
    }
    #[derive(Debug, Copy, Clone, Arbitrary, PartialEq, Eq, Default)]
    pub enum KeepAttribute {
        #[default]
        Keep,
        EliminateUnused,
    }
    #[derive(Debug, Copy, Clone, Arbitrary, PartialEq, Eq, Default)]
    pub enum MustUseAttribute {
        #[default]
        MayDiscard,
        MustUse,
    }
    pub enum ZeaAttribute {
        Inline(InlineAttribute),
        Align(AlignmentAttribute),
        Ordering(FieldOrderAttribute),
        Temperature(TemperatureAttribute),
        MustUse(MustUseAttribute),
        Keep(KeepAttribute),
    }
    pub enum AttributeParseError {
        InvalidKey(String),
        InvalidValueForKey(String, String),
        MissingValue(String),
    }

    static ALLOWED_VALUELESS_KEYS: &[&str] = &["inline", "hot", "cold", "must-use", "keep-unused"];
    static ALLOWED_KV_PAIRS: &[(&str, &str)] = &[
        ("inline", "never"),
        ("inline", "always"),
        ("fields", "descending"),
        ("fields", "c"),
    ];
    pub fn parse_raw_attribute(
        key: String,
        value: Option<String>,
    ) -> Result<ZeaAttribute, AttributeParseError> {
        match value {
            Some(value) => parse_raw_keyful_attribute(key, value),
            None => parse_raw_keyless_attribute(key),
        }
    }

    fn parse_raw_keyless_attribute(key: String) -> Result<ZeaAttribute, AttributeParseError> {
        match key.as_str() {
            "inline" => Ok(ZeaAttribute::Inline(InlineAttribute::Always)),
            "hot" => Ok(ZeaAttribute::Temperature(TemperatureAttribute::Hot)),
            "cold" => Ok(ZeaAttribute::Temperature(TemperatureAttribute::Cold)),
            "must-use" => Ok(ZeaAttribute::MustUse(MustUseAttribute::MayDiscard)),
            "keep-unused" => Ok(ZeaAttribute::Keep(KeepAttribute::Keep)),
            _ => Err(AttributeParseError::InvalidKey(key)),
        }
    }

    fn parse_raw_keyful_attribute(
        key: String,
        value: String,
    ) -> Result<ZeaAttribute, AttributeParseError> {
        match (key.as_str(), value.as_str()) {
            ("inline", "always") => Ok(ZeaAttribute::Inline(InlineAttribute::Always)),
            ("inline", "never") => Ok(ZeaAttribute::Inline(InlineAttribute::Never)),
            ("inline", _) => Err(AttributeParseError::InvalidValueForKey(key, value)),
            ("fields", "desc") => Ok(ZeaAttribute::Ordering(FieldOrderAttribute::Descending)),
            ("fields", "c") => Ok(ZeaAttribute::Ordering(FieldOrderAttribute::ReprC)),
            ("fields", _) => Err(AttributeParseError::InvalidValueForKey(key, value)),
            _ => Err(AttributeParseError::InvalidKey(key)),
        }
    }
}
