//! This crate holds the AST definition for the Zea language, along with the target C AST.
use std::{fmt::Debug, hash::Hash, marker::PhantomData};

use indexmap::{
    IndexSet,
    set::{Iter, MutableValues},
};
/// The AST's for the ZEA language
pub mod ast;
mod typecheck;
pub use typecheck::typecheck_module;
mod impls;
pub mod visualisation;

pub trait ZeaError<'m> {
    type ErrContext;
    fn zea_error_format(&'m self, ctx: &'m Self::ErrContext) -> String;
}

/// An interning table generic over its key and value.
/// A key is commonly a Newtype for some integer type, i.e. a `struct SomeID(usize);`
/// Care must to taken to only use keys that are generated by the `.intern()` method of the corresponding table,
/// as it guarantees non-panicking access.
#[derive(PartialEq, Eq, Clone)]
pub struct InternTable<Key: From<usize> + Into<usize>, Value: Hash + Eq> {
    set: IndexSet<Value>,
    phantom: PhantomData<Key>,
}

impl<Key: From<usize> + Into<usize> + Debug, Value: Hash + Eq + Debug> Debug
    for InternTable<Key, Value>
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("InternTable")
            .field("set", &self.set)
            .finish()
    }
}

impl<Key: From<usize> + Into<usize>, Value: Hash + Eq> InternTable<Key, Value> {
    pub fn new() -> Self {
        Self {
            set: IndexSet::new(),
            phantom: PhantomData,
        }
    }
    pub fn intern(&mut self, item: Value) -> Key {
        let (idx, _) = self.set.insert_full(item);
        idx.into()
    }
    pub fn get_by_id(&self, id: Key) -> Option<&Value> {
        self.set.get_index(id.into())
    }
    pub fn get_unchecked(&self, item: &Value) -> Key {
        self.set
            .get_index_of(item)
            .expect("non-interned item in intern table")
            .into()
    }
    pub fn iter(&self) -> Iter<'_, Value> {
        self.set.iter()
    }

    fn get_mut_by_id(&mut self, id: Key) -> Option<&mut Value> {
        self.set.get_index_mut2(id.into())
    }
}
impl<Key: From<usize> + Into<usize>, Value: Hash + Eq> Default for InternTable<Key, Value> {
    fn default() -> Self {
        Self::new()
    }
}
macro_rules! impl_nodelabeler {
    ($typ:ident, $label:literal) => {
        impl NodeLabeler for $typ {
            fn labeler_from(mut other_generator: impl NodeLabeler) -> Self {
                Self {
                    label: other_generator.next_id().0,
                }
            }
            fn next_id(&mut self) -> NodeId {
                let label = self.label;
                self.label += 1;
                NodeId(label)
            }
            fn next_label_with_ident_string(&mut self) -> (NodeId, String) {
                let label = self.next_id();
                (label, format!(concat!("__", $label, "{}"), label))
            }
        }
    };
    ($typ:ident) => {
        impl NodeLabeler for $typ {
            fn labeler_from(mut other_generator: impl NodeLabeler) -> Self {
                Self {
                    label: other_generator.next_id().0,
                }
            }
            fn next_id(&mut self) -> NodeId {
                let label = self.label;
                self.label += 1;
                NodeId(label)
            }
            fn next_label_with_ident_string(&mut self) -> (NodeId, String) {
                let label = self.next_id();
                (label, format!("__synthetic{}", label))
            }
        }
    };
}
pub(crate) use impl_nodelabeler;
