//! This module contains the lowering of Immediate-Parsed-Representation (IPR) into Typed-Highlevel-Representation (THR)
//! The main difference between these two is that IPR is a tree,
//! whereas THR is flat and has a bunch of interning tables that hold its nodes.
//! Instead of [`Box`]'es,
//! you have indices into the interning tables.
//!
//! The interning tables are instatiations of the [`KeySet<Key, Value>`] generic type,
//! which is itself an ergonomic wrapper around an [`IndexSet`].
//! The `Key` is often a newtype wrapper around [`usize`].
//!
//!
//! The two structs that play a key role in the lowering process are [`THRKeySets`] and [`IPRLoweringContext`]:
//! - [`IPRLoweringContext`] contains an [`IPRModule`] along with all the hashmaps generated by visitor passes,
//!   like type information, identifier resolution etc., everything necessary to infer all properties of a given node.
//! - [`THRKeySets`] contains a bunch of interning tables for :
//!     - types
//!     - symbols
//!     - expressions
//!     - statements
//!     - control-flow-blocks.
//!
//! An [`IPRModule`] can be lowered into THR by using the [`lower_module`] function,
//! which (should be?) infallible
//! as every prior visitor pass validates some set of properties of the AST.
//!
//! the [`lower_module`] call will construct an [`THRModule`], which contains the [`THRKeySets`],
//! and the ID of the synthesized block that instantiate the global variables.
//!
//! Any `lower_[node]()` method of the [`THRKeySets`] will guarantee the following:
//! - After the call returns, all descendant nodes of the supplied node will be interned
//! - An ID (or ID's) will be returned which points to the lowered version of the supplied node.
//!
//! The returned ID is used for constructing nodes wihch hold references,
//! like the `.value` or `.symbol` field in an [`THRInit`].
//!
//! At this stage, structs are also lowered into [`THRStructLayout`]'s,
//! from which you can get byte-offsets for fields, their size and alignment.
//!
//! What the THR does not directly provide is a control flow graph (CFG),
//! This is done by a later visitor pass,
//! which provides a way to get the pred- and successors of a [`THRBlock`],
//! which is then used by QBE or some other backend to generate its CFG.
//!
//!
//!
//! Grammar constructs are lowered as folllows:
//!
//! a block b in the following form:
//!
//! Since Zea is a value-oriented language, most constructs  evaluate to some kind of value.
//! a block `{ var := val; var }` would evaulate to whatever `val` is,
//! while `{ var := val; }` evaluates to `()`.
//! likewise a branch `if cond { val1 } else { val2 }`
//! (with `var1` and `var2` having the same type) would evaluate to
//! one of the two `val`'s depending on `cond`. Each value-full construct emits a [`THRInit`]
//! that assigns the constructs value to a syhnthesized, unique label like `_thr_construct1`
//! or something similar (I will decide on that later)
//!
//! So the code
//! ```
//! a := { var := 3; var};
//! ```
//!
//! lowers into:
//! ```
//! @blockN
//!   var := 3;
//!   _thr_construct1 := var;
//!   a := _thr_construct1;
//! ```
//!
//!

use std::collections::HashMap;

use rayon::prelude::*;

use crate::{
    ScalarTypeWidth,
    ast::{
        BinOp, UnOp,
        ipr::{
            IPRBlockExpression, IPRExpression, IPRExpressionKind, IPRFunction,
            IPRInitializationBlock, IPRInitializationKind, IPRModule, IPRSimpleInitialization,
            IPRStatement, IPRStatementKind, IPRTypeSpecifier, IPRTypedIdentifier,
        },
        ipr_walkers::{transformers::IdentifierScoper, visitors::SymbolKind},
    },
    attributes::{ZeaAttribute, ZeaFunctionAttributes},
};
use crate::{ast::NodeId, typecheck::IPRModuleTypeInfo};
use idset::{InternKey, KeySet, KeyVec, PreKeyVec, internkey};
use log::trace;
use zea_common::{
    CompilerConfig, CompilerError, CompilerErrorKind, CompilerStage, ModuleType,
    internal_compiler_error,
};
use zea_internal_macros::InternKey;

pub fn lower_module(
    module: IPRModule,
    types: IPRModuleTypeInfo,
    ident_scopes: IdentifierScoper,
    compiler_config: &CompilerConfig,
) -> Result<THRModule, CompilerError> {
    let thr_ctx = THRKeySets::with_integer_types();
    let ipr_ctx = IPRLoweringContext {
        module,
        types,
        ident_scopes,
    };
    thr_ctx.lower_module(&ipr_ctx, compiler_config)
}

internkey!(THRTypeID);

impl THRTypeID {
    fn alignment(self, ctx: &THRKeySets) -> usize {
        let ty = ctx
            .types
            .get_by_id(self)
            .expect("struct field name should be interned at this point");
        match ty {
            THRTypeSpecifier::Integer { width, signed: _ } => *width as usize,
            THRTypeSpecifier::Float { width } => *width as usize,
            THRTypeSpecifier::Pointer(inner) => inner.alignment(ctx),
            THRTypeSpecifier::Boolean => 1,
            THRTypeSpecifier::Unit => 0,
            THRTypeSpecifier::Never => 0,
            THRTypeSpecifier::Struct { name: _, layout } => layout.alignment(ctx),
            THRTypeSpecifier::Tuple(layout) => layout.alignment(ctx),
        }
    }

    fn width(self, ctx: &THRKeySets) -> usize {
        let ty = ctx
            .types
            .get_by_id(self)
            .expect("struct field name should be interned at this point");
        match ty {
            THRTypeSpecifier::Integer { width, signed: _ } => *width as usize,
            THRTypeSpecifier::Float { width } => *width as usize,
            THRTypeSpecifier::Pointer(inner) => inner.width(ctx),
            THRTypeSpecifier::Boolean => 1,
            THRTypeSpecifier::Unit => 0,
            THRTypeSpecifier::Never => 0,
            THRTypeSpecifier::Struct { name: _, layout } => layout.width(ctx),
            THRTypeSpecifier::Tuple(layout) => layout.width(ctx),
        }
    }
}
internkey!(THRExprID);
internkey!(THRSymbolID);
internkey!(THRStatementID);
internkey!(THRFunctionID);

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct THRModule {
    interned: THRKeySets,
    global_data_block: Vec<THRStatementID>,
    start_symbol: Option<THRFunctionID>,
    pub name: String,
    ipr_id: NodeId,
}

impl THRModule {
    pub fn global_data_block(&self) -> &[THRStatementID] {
        &self.global_data_block
    }

    pub fn entry_point(&self) -> Option<THRFunctionID> {
        self.start_symbol
    }

    pub fn get_type(&self, typ: THRTypeID) -> &THRTypeSpecifier {
        self.interned.types.get_by_id(typ).unwrap()
    }
    pub fn get_type_of_expr(&self, expr: THRExprID) -> Option<THRTypeID> {
        self.interned.expr_types.get(&expr).copied()
    }
    pub fn get_function(&self, func: THRFunctionID) -> &THRFunction {
        self.interned.functions.get_by_id(func).unwrap()
    }
    pub fn functions(&self) -> &KeySet<THRFunctionID, THRFunction> {
        &self.interned.functions
    }
    pub fn get_symbol(&self, symbol: THRSymbolID) -> &THRSymbol {
        self.interned.symbols.get_by_id(symbol).unwrap()
    }
    pub fn get_statement(&self, stmt: THRStatementID) -> &THRStatement {
        self.interned.statements.get_by_id(stmt).unwrap()
    }
    pub fn get_expr(&self, expr: THRExprID) -> &THRExpression {
        self.interned.expressions.get_by_id(expr).unwrap()
    }
    pub fn alignment_of_layout(&self, typ: &THRStructValueLayout) -> usize {
        typ.alignment(&self.interned)
    }
    pub fn width_of(&self, typ: THRTypeID) -> usize {
        typ.width(&self.interned)
    }

    pub fn alignment_of(&self, typ: THRTypeID) -> usize {
        typ.alignment(&self.interned)
    }
}

#[derive(Clone, PartialEq, Eq, Default)]
pub struct THRKeySets {
    expressions: KeySet<THRExprID, THRExpression>,
    symbols: KeySet<THRSymbolID, THRSymbol>,
    types: KeySet<THRTypeID, THRTypeSpecifier>,
    statements: KeySet<THRStatementID, THRStatement>,
    functions: KeySet<THRFunctionID, THRFunction>,
    expr_types: HashMap<THRExprID, THRTypeID>,
    thr_construct_eval_counter: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum THRTypeSpecifier {
    Integer {
        width: ScalarTypeWidth,
        signed: bool,
    },
    Float {
        width: ScalarTypeWidth,
    },
    Pointer(THRTypeID),
    Boolean,
    Unit,
    Never,
    Struct {
        name: Box<str>,
        layout: THRStructValueLayout,
    },
    Tuple(THRStructValueLayout),
}

impl THRTypeSpecifier {
    pub const fn int_signed(width: ScalarTypeWidth) -> Self {
        Self::Integer {
            width,
            signed: true,
        }
    }
    pub const fn int_unsigned(width: ScalarTypeWidth) -> Self {
        Self::Integer {
            width,
            signed: false,
        }
    }
}
/// The layout of some struct-type
///
/// This layout has the field-ordering applied already
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct THRStructValueLayout {
    pub fields: Box<[THRStructField]>,
    /// field names, used to emit debug info
    ///
    /// These are resolved to offsets during the lowering into THR
    pub debug_field_names: Box<[Box<str>]>,
}
impl THRStructValueLayout {
    pub fn alignment(&self, ctx: &THRKeySets) -> usize {
        self.fields
            .par_iter()
            .map(|field| field.typ.alignment(ctx))
            .max()
            .unwrap_or(1usize)
    }

    pub fn width(&self, ctx: &THRKeySets) -> usize {
        let struct_alignment = self.alignment(ctx);
        let summed_fields: usize = self.fields.par_iter().map(|f| f.typ.width(ctx)).sum();
        summed_fields.next_multiple_of(struct_alignment)
    }
    pub fn offset_of_field_idx(&self, field_idx: usize) -> Option<usize> {
        self.fields.get(field_idx).map(|f| f.offset)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct THRStructField {
    pub typ: THRTypeID,
    pub offset: usize,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum THRExpression {
    ConstInt(TypedLiteral<u64>),
    ConstFloat(TypedLiteral<f64>),
    ConstBool(bool),
    Binop(BinOp, THRExprID, THRExprID),
    Unop(UnOp, THRExprID),
    Ident(THRSymbolID),
}

impl THRExpression {
    pub const fn const_int(value: u64, typ: THRTypeID) -> THRExpression {
        let literal = TypedLiteral { value, typ };
        THRExpression::ConstInt(literal)
    }
    pub const fn binop(op: BinOp, lhs: THRExprID, rhs: THRExprID) -> THRExpression {
        Self::Binop(op, lhs, rhs)
    }
}

/// used to provide an Eq and Hash impl for floats.
pub trait NumericLiteral: Copy + Clone + PartialEq {
    fn canonical(self) -> Self;
}

impl NumericLiteral for u64 {
    fn canonical(self) -> Self {
        self
    }
}

impl NumericLiteral for f64 {
    fn canonical(self) -> Self {
        if self.is_nan() { f64::NAN } else { self }
    }
}
impl NumericLiteral for bool {
    fn canonical(self) -> Self {
        self
    }
}

#[derive(Debug, Clone, Copy)]
pub struct TypedLiteral<T: NumericLiteral> {
    pub typ: THRTypeID,
    pub value: T,
}

impl<T: NumericLiteral> PartialEq for TypedLiteral<T> {
    fn eq(&self, other: &Self) -> bool {
        self.typ == other.typ && self.value.canonical() == other.value.canonical()
    }
}
impl<T: NumericLiteral> Eq for TypedLiteral<T> {}

impl std::hash::Hash for TypedLiteral<f64> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.typ.hash(state);
        self.value.canonical().to_bits().hash(state);
    }
}
impl std::hash::Hash for TypedLiteral<u64> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.typ.hash(state);
        self.value.hash(state);
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum THRStatement {
    Init {
        decl: THRSymbolDecl,
        val: THRExprID,
        /// this node's corresponding NodeID from the IPR representation
        ipr_id: NodeId,
    },
    Branch {
        cond: THRExprID,
        bthen: Box<[THRStatementID]>,
        belse: Box<[THRStatementID]>,
    },
    Ret(THRExprID),
}

/// A symbol declaration, binds a symbol to a type
///
/// Used mostly in [`THRStatements`], and ident-expressions in [`THRExpressions`]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct THRSymbolDecl {
    pub symbol: THRSymbolID,
    pub typ: THRTypeID,
}
impl THRSymbolDecl {
    fn new(symbol: THRSymbolID, typ: THRTypeID) -> Self {
        Self { symbol, typ }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct THRFunction {
    pub name: Box<str>,
    pub params: Box<[THRSymbolDecl]>,
    pub body: Box<[THRStatementID]>,
    pub returns: THRTypeID,
    pub attributes: ZeaFunctionAttributes,
    pub ipr_id: NodeId,
}

impl THRFunction {
    pub fn new(
        name: String,
        params: Vec<THRSymbolDecl>,
        body: Vec<THRStatementID>,
        returns: THRTypeID,
        attributes: ZeaFunctionAttributes,
        ipr_id: NodeId,
    ) -> Self {
        Self {
            name: name.into_boxed_str(),
            params: params.into_boxed_slice(),
            body: body.into_boxed_slice(),
            returns,
            attributes,
            ipr_id,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct THRSymbol {
    pub name: Box<str>,
    pub kind: SymbolKind,
}

impl THRSymbol {
    pub fn new(name: String, kind: SymbolKind) -> Self {
        Self {
            name: name.into_boxed_str(),
            kind,
        }
    }
    pub fn func_param(name: String) -> Self {
        Self::new(name, SymbolKind::FunctionParam)
    }
    pub fn local(name: String) -> Self {
        Self::new(name, SymbolKind::LocalVar)
    }
}

static THR_INTEGER_TYPES: [THRTypeSpecifier; 8] = [
    THRTypeSpecifier::int_signed(ScalarTypeWidth::_8),
    THRTypeSpecifier::int_signed(ScalarTypeWidth::_16),
    THRTypeSpecifier::int_signed(ScalarTypeWidth::_32),
    THRTypeSpecifier::int_signed(ScalarTypeWidth::_64),
    THRTypeSpecifier::int_unsigned(ScalarTypeWidth::_8),
    THRTypeSpecifier::int_unsigned(ScalarTypeWidth::_16),
    THRTypeSpecifier::int_unsigned(ScalarTypeWidth::_32),
    THRTypeSpecifier::int_unsigned(ScalarTypeWidth::_64),
];

impl THRKeySets {
    /// Generate an identifier for a language construct
    ///
    /// i.e. a block:
    ///
    /// ```
    /// a := { 3 };
    /// ```
    ///
    /// becomes:
    ///
    /// ```
    /// ThrConstruct.0 := 3;
    /// a := ThrConstruct.0;
    /// ```
    pub fn label_construct_eval(&mut self, kind: SymbolKind) -> THRSymbolID {
        let name = format!("ThrConstruct.{}", self.thr_construct_eval_counter);
        let symb = THRSymbol {
            name: name.into_boxed_str(),
            kind,
        };
        self.symbols.get_or_intern(symb)
    }

    pub fn with_integer_types() -> Self {
        let mut s = Self::default();
        for t in THR_INTEGER_TYPES.as_slice() {
            s.types.get_or_intern(t.clone());
        }
        s
    }

    fn lower_type(
        &mut self,
        _ipr_ctx: &IPRLoweringContext,
        iprtype: &IPRTypeSpecifier,
    ) -> THRTypeID {
        let t = match iprtype {
            IPRTypeSpecifier::NonScalar(_a) => {
                todo!();
                // let s = ctx
                //     .struct_definitions
                //     .iter()
                //     .find(|s| s.name == *a)
                //     .expect("type checking should resolve struct names");
                // for IPRTypedIdentifier { name, typ } in s.members.iter() {
                //     let typ = self.lower_type(typ, ctx);
                //     let field = THRStructField {
                //         name: name.clone(),
                //         typ,
                //         offset: 0,
                //     };
                // }

                // todo!()
            }
            IPRTypeSpecifier::Unit => THRTypeSpecifier::Unit,
            IPRTypeSpecifier::Bool => THRTypeSpecifier::Boolean,
            IPRTypeSpecifier::Integer { width, signed } => {
                if *signed {
                    THRTypeSpecifier::int_signed(*width)
                } else {
                    THRTypeSpecifier::int_unsigned(*width)
                }
            }
            IPRTypeSpecifier::Float { width } => THRTypeSpecifier::Float { width: *width },
            IPRTypeSpecifier::Pointer(inner) => {
                let inner_id = self.lower_type(_ipr_ctx, inner);
                THRTypeSpecifier::Pointer(inner_id)
            }
            IPRTypeSpecifier::ArrayOf(_) => todo!("implement array types"),
            IPRTypeSpecifier::Never => THRTypeSpecifier::Never,
            IPRTypeSpecifier::UserDefined(name) => todo!(),
        };
        self.types.get_or_intern(t)
    }

    fn lower_expression(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        expr: &IPRExpression,
    ) -> (THRExprID, THRTypeID) {
        let ipr_t = ipr_ctx.types.lookup(expr.id);
        let thr_t = self.lower_type(ipr_ctx, ipr_t);
        let node = match &expr.kind {
            IPRExpressionKind::Unit => todo!(),
            IPRExpressionKind::IntegerLiteral(i) => THRExpression::const_int(*i as u64, thr_t),
            IPRExpressionKind::BoolLiteral(b) => THRExpression::ConstBool(*b),
            IPRExpressionKind::FloatLiteral(_) => todo!(),
            IPRExpressionKind::StringLiteral(_) => todo!(),
            IPRExpressionKind::ScopedIdent(i) => {
                let symbol = THRSymbol {
                    name: i.ident.clone().into_boxed_str(),
                    kind: i.kind,
                };
                let symbol = self.symbols.get_or_intern(symbol);
                THRExpression::Ident(symbol)
            }
            IPRExpressionKind::FunctionCall(_iprfunction_call) => {
                todo!()
            }
            IPRExpressionKind::BinOpExpr(op, l, r) => {
                let (l, _) = self.lower_expression(ipr_ctx, l.as_ref());
                let (r, _) = self.lower_expression(ipr_ctx, r.as_ref());
                THRExpression::binop(*op, l, r)
            }
            IPRExpressionKind::UnOpExpr(_op, _arg) => {
                todo!()
            }
            IPRExpressionKind::MemberAccess(_iprexpression, _) => {
                todo!()
            }
            IPRExpressionKind::IfThenElse(_iprbranch) => {
                todo!()
            }
            IPRExpressionKind::Block(_b) => todo!(),
            IPRExpressionKind::UnScopedIdent(_) => internal_compiler_error!(sui),
        };
        let e = self.expressions.get_or_intern(node);
        self.expr_types.insert(e, thr_t);
        (e, thr_t)
    }

    fn lower_stmt(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        stmt: &IPRStatement,
    ) -> Result<Vec<THRStatementID>, CompilerError> {
        match &stmt.kind {
            IPRStatementKind::Initialization(init) => {
                let recursive_inits = self.lower_init_block(ipr_ctx, init, SymbolKind::LocalVar)?;
                Ok(recursive_inits)
            }
            IPRStatementKind::Reassignment(_iprreassignment) => Ok(todo!()),
            IPRStatementKind::FunctionCall(_iprfunction_call) => Ok(todo!()),
            IPRStatementKind::Return(_iprexpression) => Ok(todo!()),
            IPRStatementKind::Block(_iprblock_expression) => Ok(todo!()),
            IPRStatementKind::IfThenElse(_iprbranch) => Ok(todo!()),
        }
    }

    fn lower_init_block(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        init_block: &IPRInitializationBlock,
        kind: SymbolKind,
    ) -> Result<Vec<THRStatementID>, CompilerError> {
        let IPRInitializationKind::Unpacked(inits) = &init_block.kind else {
            internal_compiler_error!(spi)
        };
        Ok(inits
            .iter()
            .map(|init| self.lower_init_single(ipr_ctx, init, kind))
            .collect())?
    }

    /// Lower a single IPR initialization
    ///
    /// recursively emits statements necessary to compute the value of this one
    fn lower_init_single(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        init: &IPRSimpleInitialization,
        kind: SymbolKind,
    ) -> Result<THRStatementID, CompilerError> {
        let symbol = THRSymbol {
            name: init.assignee.clone().into_boxed_str(),
            kind,
        };
        let symbol = self.symbols.get_or_intern(symbol);
        let (value, value_t) = self.lower_expression(ipr_ctx, &init.value);

        let tail_eval_init = THRStatement::Init {
            decl: THRSymbolDecl {
                symbol,
                typ: value_t,
            },
            val: value,
            ipr_id: init.id,
        };
        Ok(self.statements.get_or_intern(tail_eval_init))
    }

    fn lower_module(
        mut self,
        ipr_ctx: &IPRLoweringContext,
        compiler_config: &CompilerConfig,
    ) -> Result<THRModule, CompilerError> {
        let globs = &ipr_ctx.module.global_vars;
        let mut global_data_block: Vec<THRStatementID> = vec![];
        for glob in globs.iter() {
            trace!("lowering global {}", glob.id);
            let ids = self.lower_init_block(ipr_ctx, glob, SymbolKind::GlobalVar)?;
            global_data_block.extend(ids);
        }

        let funcs = &ipr_ctx.module.functions;
        let mut entry_point = None;
        for f in funcs.iter() {
            let func_id: THRFunctionID = self.lower_function(ipr_ctx, f)?;
            if f.name == "main" && compiler_config.module_type() == ModuleType::Bin {
                entry_point = Some(func_id);
            }
        }
        if entry_point.is_none() && compiler_config.module_type() == ModuleType::Bin {
            return Err(CompilerError::new(
                CompilerStage::IPRtoTHR,
                CompilerErrorKind::NoEntryPoint,
            ));
        }
        Ok(THRModule {
            interned: self,
            global_data_block,
            start_symbol: entry_point,
            name: ipr_ctx.module.name.clone(),
            ipr_id: ipr_ctx.module.id,
        })
    }

    fn lower_function(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        IPRFunction {
            attributes,
            id,
            name,
            params,
            returns,
            body,
        }: &IPRFunction,
    ) -> Result<THRFunctionID, CompilerError> {
        let returns = self.lower_type(ipr_ctx, returns);

        let mut thr_params = Vec::with_capacity(params.len());
        for param in params {
            let param_symbol = THRSymbol::new(param.name.clone(), SymbolKind::FunctionParam);
            let param_symbol = self.symbols.get_or_intern(param_symbol);
            let typ = self.lower_type(ipr_ctx, &param.typ);
            let param = THRSymbolDecl::new(param_symbol, typ);
            thr_params.push(param);
        }

        let mut thr_body = Vec::with_capacity(body.statements.len());
        for stmt in &body.statements {
            let stmts = self.lower_stmt(ipr_ctx, &stmt)?;
            thr_body.extend(stmts);
        }
        let (tail_expr, tail_expr_t) = self.lower_expression(ipr_ctx, &body.tail);
        let ret_stmt = self.statements.get_or_intern(THRStatement::Ret(tail_expr));
        thr_body.push(ret_stmt);

        let func = THRFunction::new(
            name.clone(),
            thr_params,
            thr_body,
            returns,
            *attributes,
            *id,
        );
        Ok(self.functions.get_or_intern(func))
    }

    fn lower_block(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        body: &IPRBlockExpression,
    ) -> Result<Vec<THRStatementID>, CompilerError> {
        let mut items: Vec<THRStatementID> = vec![];

        for stmt in body.statements.iter() {
            let stmts = self.lower_stmt(ipr_ctx, stmt)?;
            items.extend(stmts);
        }
        let tail_eval_init = self.synthesize_tail_expr_init(ipr_ctx, &body.tail);
        let tail = self.statements.get_or_intern(tail_eval_init);
        items.push(tail);
        Ok(items)
    }

    fn synthesize_tail_expr_init(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        tail_expr: &IPRExpression,
    ) -> THRStatement {
        let (tail_expr, tail_expr_t) = self.lower_expression(ipr_ctx, tail_expr);
        let tail_eval_decl = self.label_construct_eval(SymbolKind::LocalVar);
        let tail_eval_init = THRStatement::Init {
            decl: THRSymbolDecl {
                symbol: tail_eval_decl,
                typ: tail_expr_t,
            },
            val: tail_expr,
            ipr_id: NodeId::sentinel(),
        };
        tail_eval_init
    }
}

struct IPRLoweringContext {
    module: IPRModule,
    types: IPRModuleTypeInfo,
    ident_scopes: IdentifierScoper,
}

impl std::fmt::Debug for THRKeySets {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&"TYPES:\n\t", f)?;
        for (i, t) in self.types.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            t.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }

        std::fmt::Display::fmt(&"\rSYMBOLS:\n\t", f)?;
        for (i, s) in self.symbols.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        std::fmt::Display::fmt(&"\rEXPRESSIONS:\n\t", f)?;
        for (i, s) in self.expressions.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        std::fmt::Display::fmt(&"\rSTATEMENTS:\n\t", f)?;
        for (i, s) in self.statements.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        std::fmt::Display::fmt(&"\rFUNCTIONS:\n\t", f)?;
        for (i, s) in self.functions.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        "\n".fmt(f)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn struct_field(ctx: &mut THRKeySets, typ: THRTypeSpecifier) -> THRStructField {
        THRStructField {
            typ: ctx.types.get_or_intern(typ),
            offset: 0,
        }
    }
    fn struct_field_i8(ctx: &mut THRKeySets) -> THRStructField {
        struct_field(ctx, THRTypeSpecifier::int_signed(ScalarTypeWidth::_8))
    }
    fn struct_field_i32(ctx: &mut THRKeySets) -> THRStructField {
        struct_field(ctx, THRTypeSpecifier::int_signed(ScalarTypeWidth::_32))
    }
    fn struct_field_i64(ctx: &mut THRKeySets) -> THRStructField {
        struct_field(ctx, THRTypeSpecifier::int_signed(ScalarTypeWidth::_64))
    }
    fn struct_field_i16(ctx: &mut THRKeySets) -> THRStructField {
        struct_field(ctx, THRTypeSpecifier::int_signed(ScalarTypeWidth::_16))
    }

    fn struct_size_invariant(layout: &THRStructValueLayout, ctx: &THRKeySets) {
        let s = layout.width(ctx);
        let a = layout.alignment(ctx);
        assert_eq!(s % a, 0, "size {s} should be a multiple of alignment{a}");
    }
    fn run_layout_cases(cases: Vec<(Vec<THRStructField>, usize, usize)>, ctx: &THRKeySets) {
        for (fields, size, align) in cases {
            let s = THRStructValueLayout {
                fields: fields.into_boxed_slice(),
                debug_field_names: Box::new([]),
            };

            assert_eq!(s.width(ctx), size);
            assert_eq!(s.alignment(ctx), align);
            struct_size_invariant(&s, ctx);
        }
    }
    #[test]
    fn struct_width() {
        let mut ctx = THRKeySets::with_integer_types();
        let i8 = struct_field_i8(&mut ctx);
        let i16 = struct_field_i16(&mut ctx);
        let i32 = struct_field_i32(&mut ctx);
        let i64 = struct_field_i64(&mut ctx);

        let basic_cases = [
            (vec![i8.clone()], 1usize, 1usize),
            (vec![i8.clone(), i8.clone()], 2, 1),
            (vec![i8.clone(), i8.clone(), i8.clone(), i8.clone()], 4, 1),
            (vec![i16.clone()], 2, 2),
            (vec![i16.clone(), i16.clone()], 4, 2),
            (
                vec![i16.clone(), i16.clone(), i16.clone(), i16.clone()],
                8,
                2,
            ),
            (vec![i32.clone()], 4, 4),
            (vec![i32.clone(), i32.clone()], 8, 4),
            (
                vec![i32.clone(), i32.clone(), i32.clone(), i32.clone()],
                16,
                4,
            ),
            (vec![i64.clone()], 8, 8),
            (vec![i64.clone(), i64.clone()], 16, 8),
            (
                vec![i64.clone(), i64.clone(), i64.clone(), i64.clone()],
                32,
                8,
            ),
        ];

        let mixed_fields = [
            (vec![i16.clone(), i8.clone()], 4usize, 2usize),
            (vec![i32.clone(), i8.clone()], 8, 4),
            (vec![i32.clone(), i8.clone(), i32.clone()], 12, 4),
            (vec![i64.clone(), i8.clone()], 16, 8),
            (vec![i64.clone(), i8.clone()], 16, 8),
            (vec![i64.clone(), i8.clone(), i64.clone()], 24, 8),
        ];

        run_layout_cases(basic_cases.to_vec(), &ctx);
        run_layout_cases(mixed_fields.to_vec(), &ctx);
    }
}
