#![allow(dead_code, unused_imports)]
/// This module contains the AST definition for the Zea language.
/// Any node that encompasses some structure with meaningful data has an id, this id has the following guarantees:
/// - the id is unique
/// - there is no specified order in the id's of nodes.
/// - the ID of a node stays the same through the whole compilation process.
///
/// As such, you can use these id's as keys in hashtables tables that annotate nodes.
///
/// To maintain these invariants, any AST-visitors must not change the ID of an existing node.
/// When the visitor places a new node in the AST, that node must get a new unique ID.
///
/// To make this easier, the [`visitors::altering::NodeLabeler`] trait
/// may be implemented on a visitor.
/// This trait provides the [`visitors::altering::NodeLabeler::continue_from_last_id_of`] method
/// to maintain the generation of unique ID's.
///
/// A node having an ID of 0 signals a sentinel ID,
/// it signifies that the node still requires a unique ID.
///
/// The [`visitors::altering::BareNodeLabeler`] visitor
/// grants a unique ID to node with a sentinel ID.
use crate::helper_impls::StructuralEq;


pub mod typecheck;
pub mod visitors;

#[cfg(test)]
pub(crate) mod test_ast_macros {
    macro_rules! label_ast {
        (fresh $ast:expr) => {{
            use crate::zea::Module;
            use crate::zea::visitors::altering::{BareNodeLabeler, NodeLabeler};

            let mut node_labeler = BareNodeLabeler::new();
            let mut ast = $ast;
            ast.label_sentinel_id(node_labeler);
            (ast, generator)
        }};
        (using $l:expr ; $ast:expr) => {{
            let mut ast = $ast;
            let mut l = $l;
            ast.accept_sentinel_labeler(&mut l);
            (ast, l)
        }};
    }
    pub(crate) use label_ast;
    macro_rules! block {
        {} => {
           {
               StatementBlock {
                    id: 0,
                    statements: vec![]
               }
           }
        };
        {$($e:expr);+ $(;)?} => {
           {
               StatementBlock {
                    id: 0,
                    statements: vec![$($e),+]
               }
           }
        };
        {exp $($e:expr);+ $(;)?} => {
            {
                let be = crate::zea::BlockExpander::new();
                let mut b: Statement = stmt!(block
                StatementBlock {
                    id: 0,
                    statements: vec![$($e),+]
               };);
                b.accept_block_expander(&mut be);
                let StatementKind::ExpandedBlock(eb) = b.kind else {panic!("expected expanded block")};
                eb
            }
        }
    }

    pub(crate) use block;

    macro_rules! stmt {
        (ret $e:expr) => {
            {use crate::zea::{Statement,StatementKind};
            Statement {
                id: 0,
                kind: StatementKind::Return($e)
            }
        }};
        (block $e:expr) => {
            {
                use crate::zea::{Statement, StatementKind};
            Statement {
                id: 0,
                kind: StatementKind::Block($e)
            }
        }};
        (tail $e:expr) => {
            {use crate::zea::{Statement,StatementKind};
            Statement {
                id: 0,
                kind: StatementKind::BlockTail($e)
            }
        }};
        (call $name:ident ($($e:expr),*)) => {
            {
                use crate::zea::{Statement, StatementKind, FunctionCall}
            Statement {
                id: 0,
                kind: StatementKind::FunctionCall(FunctionCall {
                    id: 0,
                    name: $name,
                    args: vec![$($e),*]
                })
            }
        }};

        (init $p:expr ;= $val:expr) => {
            {
                use crate::zea::{AssignmentPattern,Initialization,Statement,StatementKind};
            Statement {
                id: 0,
                kind: StatementKind::Initialization(Initialization {
                    id: 0,
                    kind: InitializationKind::Packed(
                        PackedInitialization {
                    assignee: $p,
                    typ: None,
                    value: $val,
                        }
                    )
                })
            }
        }};
    }
    pub(crate) use stmt;

    // generated by claude code, prompt:
    // "can you make the pat macro a tt muncher
    // that accepts things like (a,(b,c)) and converts it to a nested assignment pattern"
    // + pat macro
    macro_rules! pat {
    // Single identifier — base case
    ($i:ident) => {
        AssignmentPattern::Identifier(String::from(stringify!($i)))
    };
    // Outer tuple — kick off the muncher with an empty accumulator
    (($($t:tt)*)) => {
        pat!(@munch [] $($t)*)
    };
    // Muncher: accumulator is complete, nothing left to consume
    (@munch [$($acc:expr),*]) => {
        AssignmentPattern::Tuple(vec![$($acc),*])
    };
    // Muncher: next item is a nested tuple, more items follow
    (@munch [$($acc:expr),*] ($($inner:tt)*), $($rest:tt)*) => {
        pat!(@munch [$($acc,)* pat!(($($inner)*))] $($rest)*)
    };
    // Muncher: next item is a nested tuple, nothing follows
    (@munch [$($acc:expr),*] ($($inner:tt)*)) => {
        pat!(@munch [$($acc,)* pat!(($($inner)*))])
    };
    // Muncher: next item is an identifier, more items follow
    (@munch [$($acc:expr),*] $i:ident, $($rest:tt)*) => {
        pat!(@munch [$($acc,)* pat!($i)] $($rest)*)
    };
    // Muncher: next item is an identifier, nothing follows
    (@munch [$($acc:expr),*] $i:ident) => {
        pat!(@munch [$($acc,)* pat!($i)])
    };

}
    pub(crate) use pat;
    macro_rules! expr {
        (ident $($l:tt)+) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::Ident(String::from(stringify!($($l)+))),
            }
        }};
        (litint $l:literal) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::IntegerLiteral($l),
            }
        }};
        (litfloat $l:literal) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::FloatLiteral($l),
            }
        }};
        (litbool $l:literal) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::BoolLiteral($l),
            }
        }};
        (litstr $l:literal) => {
            Expression {
                id: 0,
                kind: ExpressionKind::StringLiteral(stringify!($l)),
            }
        };
        (unit) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::Unit,
            }
        }};
        (block $block:expr) => {{
            use crate::zea::{Expression,ExpressionKind,StatementBlock};
            Expression {
                id: 0,
                kind: ExpressionKind::Block($block)
            }
            }
        }
    }
    pub(crate) use expr;

    macro_rules! zea_module {
        (imports {$($imp:ident),* $(,)?}
         exports {$($exp:ident),* $(,)?}
         globs   {$($glob:expr);* $(;)?}
         funcs   {$($func:expr);* $(;)?}
         structs {$($struct_def:expr);* $(;)?}
        ) => {
            {
                use crate::zea::Module;
                Module {
                    id: 0,
                    imports: vec![$(String::from(stringify!($imp))),*],
                    exports: vec![$(String::from(stringify!($exp))),*],
                    global_vars: vec![$($glob),*],
                    functions: vec![$($func),*],
                    struct_definitions: vec![$($struct_def),*]
                }
            }
        };
    }
    pub(crate) use zea_module;
    macro_rules! func {
        {$name:ident ( $($arg:ident: $typ:expr),* ) -> $ret:expr; { $body:expr }} => {
            {
                use crate::zea::{Function, TypedIdentifier};
                let args = vec![$(
                TypedIdentifier(String::from(stringify!($arg)), $typ)
                ),*];
                Function {
                    id: 0,
                    name: String::from(stringify!($name)),
                    params:args,
                    returns: $ret,
                    body: $body,
                }
            }
        };
    }
    pub(crate) use func;
    macro_rules! ztyp {
        ($t:ident) => {
            {
            use crate::zea::TypeSpecifier;
                TypeSpecifier::Basic(String::from(stringify!($t)))
            }
        };
        (*$($t:tt)+) => {
            {
            use crate::zea::TypeSpecifier;
                TypeSpecifier::Pointer(Box::new(ztyp!($($t)+)))
            }
        };
        ([ ]$($t:tt)+) => {
            {
            use crate::zea::TypeSpecifier;
                TypeSpecifier::ArrayOf(Box::new(ztyp!($($t)+)))
            }
        };
    }
    pub(crate) use ztyp;
}

pub use crate::zea::visitors::altering::{BareNodeLabeler, BlockExpander, NodeLabeler};
use std::fmt::{Debug, Formatter};
use std::hash::{Hash, Hasher};
use zea_macros::{ASTStructuralEq, HashEqById, VariantToStr};

#[derive(Default, HashEqById, Debug, ASTStructuralEq)]
pub struct Module {
    pub id: usize,
    pub imports: Vec<String>,
    pub exports: Vec<String>,
    pub global_vars: Vec<Initialization>,
    pub functions: Vec<Function>,
    pub struct_definitions: Vec<StructDataTypeDefinition>,
}

impl Module {
    pub fn find_entry_point(&self) -> Option<&Function> {
        self.iter_functions().find(|func| func.name == "main")
    }

    pub fn iter_functions(&self) -> impl Iterator<Item = &Function> {
        self.functions.iter()
    }
    pub fn iter_global_vars(&self) -> impl Iterator<Item = &Initialization> {
        self.global_vars.iter()
    }
    pub fn iter_structs(&self) -> impl Iterator<Item = &StructDataTypeDefinition> {
        self.struct_definitions.iter()
    }
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct FuncParam {
    id: usize,
    pub typ: TypeSpecifier,
    pub name: String,
}
impl From<TypedIdentifier> for FuncParam {
    fn from(value: TypedIdentifier) -> Self {
        Self {
            id: 0,
            typ: value.typ,
            name: value.name,
        }
    }
}

/// A top-level function definition
///
/// Function may be defined only once within a module.
/// Functions may be imported as many times as needed.
#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Function {
    pub id: usize,
    pub name: String,
    pub params: Vec<FuncParam>,
    pub returns: TypeSpecifier,
    pub body: StatementBlock,
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct HoistedFunctionSignature {
    pub id: usize,
    pub name: String,
    pub args: Vec<FuncParam>,
    pub returns: TypeSpecifier,
}

impl From<Function> for HoistedFunctionSignature {
    fn from(value: Function) -> Self {
        HoistedFunctionSignature {
            id: value.id,
            name: value.name,
            args: value.params,
            returns: value.returns,
        }
    }
}
#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Statement {
    pub id: usize,
    pub kind: StatementKind,
}

#[derive(Debug, Clone, PartialEq, VariantToStr, ASTStructuralEq)]
pub enum StatementKind {
    // initial pass
    /// Variable initialization
    Initialization(Initialization),
    /// Variable Reassignment
    Reassignment(Reassignment),
    FunctionCall(FunctionCall),
    /// Control-flow return
    Return(Expression),
    /// A tailing expression in a block
    BlockTail(Expression),

    /// A Block of statements
    Block(StatementBlock),
    // CondMatch(Box<ConditionMatch>),

    // after expansion
    ExpandedBlock(ExpandedBlockExpr),
    IfThenElse(IfThenElse),
}
#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Initialization {
    pub id: usize,
    pub kind: InitializationKind,
}

impl Initialization {
    pub fn packed(
        typ: Option<TypeSpecifier>,
        assignee: AssignmentPattern,
        value: Expression,
    ) -> Self {
        Self {
            id: 0,
            kind: InitializationKind::Packed(PackedInitialization {
                typ,
                assignee,
                value,
            }),
        }
    }
}

#[derive(Debug, Clone, Eq, PartialEq, ASTStructuralEq)]
pub struct PackedInitialization {
    pub typ: Option<TypeSpecifier>,
    pub assignee: AssignmentPattern,
    pub value: Expression,
}

/// An assignment to a simple, totally unpacked variable.
#[derive(Debug, Clone, Eq, PartialEq, ASTStructuralEq)]
pub struct SimpleInitialization {
    id: usize,
    pub typ: Option<TypeSpecifier>,
    pub assignee: String,
    pub value: Expression,
}
impl SimpleInitialization {
    pub fn untyped(assignee: &str, value: Expression) -> Self {
        Self {
            id: 0,
            assignee: assignee.to_string(),
            value,
            typ: None,
        }
    }
}

#[derive(Debug, Clone, Eq, PartialEq, ASTStructuralEq)]
pub struct PartiallyUnpackedInitialization {
    pub temporary: SimpleInitialization,
    pub unpacked_assignments: Vec<Initialization>,
}
#[derive(Debug, Clone, Eq, PartialEq, ASTStructuralEq)]
pub enum InitializationKind {
    Packed(PackedInitialization),
    PartiallyUnpacked(PartiallyUnpackedInitialization),
    Unpacked(Vec<SimpleInitialization>),
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Reassignment {
    pub id: usize,
    pub assignee: String,
    pub value: Expression,
}
impl Reassignment {
    pub fn wrap_in_statement(self) -> Statement {
        Statement {
            id: 0,
            kind: StatementKind::Reassignment(self),
        }
    }
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct HoistedDeclaration {
    pub id: usize,
    pub typ: TypeSpecifier,
    pub assignee: String,
    pub value: Expression,
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct FunctionCall {
    pub id: usize,
    pub name: String,
    pub args: Vec<Expression>,
}

impl FunctionCall {
    pub fn wrap_in_statement(self) -> Statement {
        Statement {
            id: 0,
            kind: StatementKind::FunctionCall(self),
        }
    }

    pub fn wrap_in_expression(self) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::FunctionCall(self),
        }
    }
}
#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct StatementBlock {
    pub id: usize,
    pub statements: Vec<Statement>,
}
impl StatementBlock {
    pub fn wrap_in_expression(self) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::Block(self),
        }
    }
    pub fn wrap_in_statement(self) -> Statement {
        Statement {
            id: 0,
            kind: StatementKind::Block(self),
        }
    }
}

impl IntoIterator for StatementBlock {
    type Item = Statement;
    type IntoIter = <Vec<Statement> as IntoIterator>::IntoIter;
    fn into_iter(self) -> Self::IntoIter {
        self.statements.into_iter()
    }
}
impl StatementBlock {
    pub fn as_slice(&self) -> &[Statement] {
        self.statements.as_slice()
    }
}

#[derive(Clone, Debug, PartialEq, ASTStructuralEq)]
pub struct ExpandedBlockExpr {
    /// The label that the block expression has its value assigned to
    /// i.e. `__block0`, `__block1` etc.
    /// This label must be unique to the scope of the function in which it exists
    pub id: usize,
    pub statements: Vec<Statement>,
    pub last: Expression,
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Expression {
    pub id: usize,
    pub kind: ExpressionKind,
}

impl Expression {
    pub fn tuple_member_access(e: Expression, field: usize) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::MemberAccess(Box::new(e), format!("_{field}")),
        }
    }

    pub fn ident(ident: &str) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::Ident(ident.to_string()),
        }
    }

    pub fn wrap_in_return_statement(self) -> Statement {
        Statement {
            id: 0,
            kind: StatementKind::Return(self),
        }
    }

    pub fn wrap_in_block_tail_statement(self) -> Statement {
        Statement {
            id: 0,
            kind: StatementKind::BlockTail(self),
        }
    }

    pub fn wrap_lit_int(i: u64) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::IntegerLiteral(i),
        }
    }
    pub fn wrap_lit_float(f: f64) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::FloatLiteral(f),
        }
    }

    pub fn wrap_lit_bool(b: bool) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::BoolLiteral(b),
        }
    }

    pub fn wrap_ident(ident: String) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::Ident(ident),
        }
    }
}

#[derive(Debug, Clone, PartialEq, VariantToStr, ASTStructuralEq)]
pub enum ExpressionKind {
    // initial pass
    Unit,
    IntegerLiteral(u64),
    BoolLiteral(bool),
    FloatLiteral(f64),
    StringLiteral(String),
    Ident(String),
    FunctionCall(FunctionCall),
    BinOpExpr(BinOp, Box<Expression>, Box<Expression>),
    UnOpExpr(UnOp, Box<Expression>),
    MemberAccess(Box<Expression>, String),
    IfThenElse(IfThenElse),

    Block(StatementBlock),
    // PatternMatch(PatternMatch),
    // ConditionMatch(ConditionMatch),
    // IfThenElse(IfThenElse),

    // after expansion
    ExpandedBlock(Box<ExpandedBlockExpr>),
}

impl Expression {
    pub fn unit(id: usize) -> Self {
        Expression {
            id,
            kind: ExpressionKind::Unit,
        }
    }

    pub fn binop(op: BinOp, l: Expression, r: Expression) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::BinOpExpr(op, Box::new(l), Box::new(r)),
        }
    }
    pub fn unop(op: UnOp, e: Expression) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::UnOpExpr(op, Box::new(e)),
        }
    }
    pub fn block(b: StatementBlock) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::Block(b),
        }
    }

    pub fn member_access(data: Expression, member: String) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::MemberAccess(Box::new(data), member),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, ASTStructuralEq)]
pub enum BinOp {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    LogAnd,
    LogOr,
    LogXor,
    BitAnd,
    BitOr,
    BitXor,
    Subscript,
    Lsh,
    Rsh,
    Eq,
    Neq,
    Geq,
    Leq,
    LT,
    GT,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, ASTStructuralEq)]
pub enum UnOp {
    Neg,
    LogNot,
    BitNot,
}

#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct ConditionMatch {
    pub id: usize,
    conditions: Vec<ConditionMatchArm>,
}

#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct PatternMatch {
    pub id: usize,
    subject: Box<Expression>,
    patterns: Vec<PatternMatchArm>,
}

#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct IfThenElse {
    pub id: usize,
    pub condition: Box<Expression>,
    pub true_case: Box<Expression>,
    pub false_case: Option<Box<Expression>>,
}
impl IfThenElse {
    pub fn if_block(condition: Expression, then: Expression) -> Self {
        IfThenElse {
            id: 0,
            condition: Box::new(condition),
            true_case: Box::new(then),
            false_case: None,
        }
    }
    pub fn if_else_block(condition: Expression, then: Expression, otherwise: Expression) -> Self {
        IfThenElse {
            id: 0,
            condition: Box::new(condition),
            true_case: Box::new(then),
            false_case: Some(Box::new(otherwise)),
        }
    }
    pub fn wrap_in_expression(self) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::IfThenElse(self),
        }
    }
    pub fn wrap_in_statement(self) -> Statement {
        Statement {
            id: 0,
            kind: StatementKind::IfThenElse(self),
        }
    }
}
#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct PatternMatchArm {
    pub id: usize,
    pat: AssignmentPattern,
    value: Box<Expression>,
}
#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct ConditionMatchArm {
    pub id: usize,
    case: Box<Expression>,
    value: Box<Expression>,
}
/// the left hand side of an assignment
///
/// The simplest is a basic identifier
#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum AssignmentPattern {
    /// the pattern
    ///
    /// `var a: ...`
    ///
    /// or
    ///
    /// `a := ...`
    Identifier(String),
    /// the pattern
    ///
    /// `(<pat>, <pat>, <pat>) := ...`
    ///
    /// or
    ///
    /// `var (a,b,c) := ...`
    Tuple(Vec<AssignmentPattern>),
}

// This manual impl exists because deriving it
// causes the compiler to say that the bound `&Vec<AssignmentPattern>: StructuralEq`
// is not satisfied, even though it is???
impl StructuralEq for AssignmentPattern {
    fn eq_ignore_id(&self, other: &Self) -> bool {
        match (self, other) {
            (AssignmentPattern::Identifier(_), AssignmentPattern::Identifier(_)) => true,
            (AssignmentPattern::Tuple(t1), AssignmentPattern::Tuple(t2)) => {
                t1.iter().zip(t2).all(|(a, b)| a.eq_ignore_id(b))
            }
            _ => false,
        }
    }
}

#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum MatchPattern {
    /// the pattern `a => ...`
    Identifier(String),
    /// the pattern `(<pat>, <pat>, ...) => ...`
    Tuple(Vec<AssignmentPattern>),

    UnionVariant(String, String, Box<AssignmentPattern>),
}

impl StructuralEq for MatchPattern {
    fn eq_ignore_id(&self, other: &Self) -> bool {
        match (self, other) {
            (MatchPattern::Identifier(_), MatchPattern::Identifier(_)) => true,
            (MatchPattern::Tuple(t1), MatchPattern::Tuple(t2)) => t1
                .iter()
                .zip(t2)
                .all(|(a, b)| StructuralEq::eq_ignore_id(a, b)),
            (MatchPattern::UnionVariant(_, _, s3), MatchPattern::UnionVariant(_, _, o3)) => {
                StructuralEq::eq_ignore_id(s3.as_ref(), o3.as_ref())
            }
            _ => false,
        }
    }
}

impl std::fmt::Display for AssignmentPattern {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        let s = match self {
            AssignmentPattern::Identifier(s) => s.clone(),
            AssignmentPattern::Tuple(tups) => {
                let s: Vec<String> = tups.iter().map(|pat| pat.to_string()).collect();
                format!("({})", s.join(", "))
            }
        };
        write!(f, "{}", s)
    }
}

/// The Zea named Struct type / product type
#[derive(HashEqById, ASTStructuralEq, Debug)]
pub struct StructDataTypeDefinition {
    pub id: usize,
    pub name: String,
    pub members: Vec<TypedIdentifier>,
}

pub struct TupleSignature {
    members: Vec<TypeSpecifier>,
}

pub struct TaggedUnionDataTypeDefinition {
    pub name: String,
    pub members: Vec<TaggedUnionVariant>,
}

pub enum TaggedUnionVariant {
    TagVariant(String),
    DataVariant(TypedIdentifier),
}

/// The Type that is bundled with a:
/// - function parameter
/// - identifier in declaration(-assignments)
#[derive(PartialEq, Eq, Clone, Hash, ASTStructuralEq)]
pub enum TypeSpecifier {
    /// Int, Bool, etc.
    Basic(String),

    /// `<type>&`
    Pointer(Box<TypeSpecifier>),
    /// `[<type>]`
    ArrayOf(Box<TypeSpecifier>),
    // /// `&[<type>]`
    // Slice(Box<Type>),
    // /// `?<type>`
    // Option(Box<Type>),
}

impl Debug for TypeSpecifier {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let str = match self {
            TypeSpecifier::Basic(typ) => typ,
            TypeSpecifier::ArrayOf(arr) => &format!("[{arr:?}]"),
            // Type::Option(opt) => &format!("?{opt:?}"),
            TypeSpecifier::Pointer(ptr) => &format!("&{ptr:?}"),
            // Type::Slice(slice) => &format!("&[{slice:?}]"),
        };

        write!(f, "{}", str)
    }
}

impl From<&str> for TypeSpecifier {
    fn from(val: &str) -> Self {
        TypeSpecifier::Basic(val.into())
    }
}

impl From<String> for TypeSpecifier {
    fn from(val: String) -> Self {
        TypeSpecifier::Basic(val)
    }
}
#[allow(non_snake_case)]
impl TypeSpecifier {
    pub fn I64() -> Self {
        Self::from("I64")
    }
    pub fn F64() -> Self {
        Self::from("F64")
    }

    pub fn Bool() -> Self {
        Self::from("Bool")
    }
    pub fn Unit() -> Self {
        Self::from("Unit")
    }

    pub fn Never() -> Self {
        Self::from("Never")
    }
}
#[derive(Debug, Eq, PartialEq, Hash, Clone, ASTStructuralEq)]
pub struct TypedIdentifier {
    pub name: String,
    pub typ: TypeSpecifier,
}

impl TypedIdentifier {
    pub fn new(typ: TypeSpecifier, name: impl Into<String>) -> Self {
        Self {
            typ,
            name: name.into(),
        }
    }
}
