#![allow(dead_code, unused_imports)]

use crate::helper_impls::{assert_structural_eq, StructuralEq};
pub mod typecheck;
pub mod visitors;

#[cfg(test)]
pub(crate) mod test_ast_macros {
    macro_rules! label_ast {
        (fresh $ast:expr) => {{
            use crate::zea::visitors::altering::BareNodeLabeler;
            let mut node_labeler = BareNodeLabeler::new();
            let mut ast = $ast;
            ast.give_unique_ids(&mut node_labeler);
            (ast, node_labeler)
        }};
        (using $l:expr ; $ast:expr) => {{
            use crate::zea::visitors::altering::BareNodeLabeler;
            let mut ast = $ast;
            ast.give_unique_ids(&mut $l);
            (ast, $l)
        }};
    }
    pub(crate) use label_ast;
    macro_rules! block {
        {} => {
           {
               StatementBlock {
                    id: 0,
                    statements: vec![]
               }
           }
        };
        {$($e:expr);+ $(;)?} => {
           {
               StatementBlock {
                    id: 0,
                    statements: vec![$($e),+]
               }
           }
        };
        {exp $($e:expr);+ $(;)?} => {
            {
                let be = crate::zea::BlockExpander::new();
                let mut b: Statement = stmt!(block
                StatementBlock {
                    id: 0,
                    statements: vec![$($e),+]
               };);
                b.accept_block_expander(&mut be);
                let StatementKind::ExpandedBlock(eb) = b.kind else {panic!("expected expanded block")};
                eb
            }
        }
    }

    pub(crate) use block;

    macro_rules! stmt {
        (ret $e:expr) => {
            {use crate::zea::{Statement,StatementKind};
            Statement {
                id: 0,
                kind: StatementKind::Return($e)
            }
        }};
        (block $e:expr) => {
            {
                use crate::zea::{Statement, StatementKind};
            Statement {
                id: 0,
                kind: StatementKind::Block($e)
            }
        }};
        (tail $e:expr) => {
            {use crate::zea::{Statement,StatementKind};
            Statement {
                id: 0,
                kind: StatementKind::BlockTail($e)
            }
        }};
        (call $name:ident ($($e:expr),*)) => {
            {
                use crate::zea::{Statement, StatementKind, FunctionCall}
            Statement {
                id: 0,
                kind: StatementKind::FunctionCall(FunctionCall {
                    id: 0,
                    name: $name,
                    args: vec![$($e),*]
                })
            }
        }};

        (init $p:expr ;= $val:expr) => {
            {
                use crate::zea::{AssignmentPattern,Initialisation,Statement,StatementKind};
            Statement {
                id: 0,
                kind: StatementKind::Initialisation(Initialisation {
                    id: 0,
                    kind: InitialisationKind::Packed(
                        PackedInitialisation {
                    assignee: $p,
                    typ: None,
                    value: $val,
                        }
                    )
                })
            }
        }};
    }
    pub(crate) use stmt;

    // generated by claude code, prompt:
    // "can you make the pat macro a tt muncher
    // that accepts things like (a,(b,c)) and converts it to a nested assignment pattern"
    // + pat macro
    macro_rules! pat {
    // Single identifier — base case
    ($i:ident) => {
        AssignmentPattern::Identifier(String::from(stringify!($i)))
    };
    // Outer tuple — kick off the muncher with an empty accumulator
    (($($t:tt)*)) => {
        pat!(@munch [] $($t)*)
    };
    // Muncher: accumulator is complete, nothing left to consume
    (@munch [$($acc:expr),*]) => {
        AssignmentPattern::Tuple(vec![$($acc),*])
    };
    // Muncher: next item is a nested tuple, more items follow
    (@munch [$($acc:expr),*] ($($inner:tt)*), $($rest:tt)*) => {
        pat!(@munch [$($acc,)* pat!(($($inner)*))] $($rest)*)
    };
    // Muncher: next item is a nested tuple, nothing follows
    (@munch [$($acc:expr),*] ($($inner:tt)*)) => {
        pat!(@munch [$($acc,)* pat!(($($inner)*))])
    };
    // Muncher: next item is an identifier, more items follow
    (@munch [$($acc:expr),*] $i:ident, $($rest:tt)*) => {
        pat!(@munch [$($acc,)* pat!($i)] $($rest)*)
    };
    // Muncher: next item is an identifier, nothing follows
    (@munch [$($acc:expr),*] $i:ident) => {
        pat!(@munch [$($acc,)* pat!($i)])
    };

}
    pub(crate) use pat;
    macro_rules! expr {
        (ident $($l:tt)+) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::Ident(String::from(stringify!($($l)+))),
            }
        }};
        (litint $l:literal) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::IntegerLiteral($l),
            }
        }};
        (litfloat $l:literal) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::FloatLiteral($l),
            }
        }};
        (litbool $l:literal) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::BoolLiteral($l),
            }
        }};
        (litstr $l:literal) => {
            Expression {
                id: 0,
                kind: ExpressionKind::StringLiteral(stringify!($l)),
            }
        };
        (unit) => {{
            use crate::zea::{Expression, ExpressionKind};
            Expression {
                id: 0,
                kind: ExpressionKind::Unit,
            }
        }};
        (block $block:expr) => {{
            use crate::zea::{Expression,ExpressionKind,StatementBlock};
            Expression {
                id: 0,
                kind: ExpressionKind::Block($block)
            }
            }
        }
    }
    pub(crate) use expr;

    macro_rules! zea_module {
        (imports {$($imp:ident),* $(,)?}
         exports {$($exp:ident),* $(,)?}
         globs   {$($glob:expr);* $(;)?}
         funcs   {$($func:expr);* $(;)?}
        ) => {
            {
                use crate::zea::Module;
                Module {
                    id: 0,
                    imports: vec![$(String::from(stringify!($imp))),*],
                    exports: vec![$(String::from(stringify!($exp))),*],
                    global_vars: vec![$($glob),*],
                    functions: vec![$($func),*],
                }
            }
        };
    }
    pub(crate) use zea_module;
    macro_rules! func {
        {$name:ident ( $($arg:ident: $typ:expr),* ) -> $ret:expr; { $body:expr }} => {
            {
                use crate::zea::{Function, TypedIdentifier};
                let args = vec![$(
                TypedIdentifier(String::from(stringify!($arg)), $typ)
                ),*];
                Function {
                    id: 0,
                    name: String::from(stringify!($name)),
                    args,
                    returns: $ret,
                    body: $body,
                }
            }
        };
    }
    pub(crate) use func;
    macro_rules! ztyp {
        ($t:ident) => {
            {
            use crate::zea::Type;
                Type::Basic(String::from(stringify!($t)))
            }
        };
        (*$($t:tt)+) => {
            {
            use crate::zea::Type;
                Type::Pointer(Box::new(ztyp!($($t)+)))
            }
        };
        ([ ]$($t:tt)+) => {
            {
            use crate::zea::Type;
                Type::ArrayOf(Box::new(ztyp!($($t)+)))
            }
        };
    }
    pub(crate) use ztyp;
}

pub use crate::zea::visitors::altering::BlockExpander;
use std::fmt::{Debug, Formatter};
use std::hash::{Hash, Hasher};
use zea_macros::{ASTStructuralEq, HashEqById, VariantToStr};

#[derive(Default, HashEqById, Debug, ASTStructuralEq)]
pub struct Module {
    pub id: usize,
    pub imports: Vec<String>,
    pub exports: Vec<String>,
    pub global_vars: Vec<Initialisation>,
    pub functions: Vec<Function>,
}

impl Module {
    pub fn find_entry_point(&self) -> Option<&Function> {
        self.iter_symbols().find(|func| func.name == "main")
    }

    pub fn iter_symbols(&self) -> impl Iterator<Item = &Function> {
        self.functions.iter()
    }
}

/// A top-level function definition
///
/// Function may be defined only once within a module, They are compared and [`Hash`]'ed against their signature.
/// Functions may be imported as many times as needed.
#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Function {
    pub id: usize,
    pub name: String,
    pub args: Vec<TypedIdentifier>,
    pub returns: Type,
    pub body: StatementBlock,
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct HoistedFunctionSignature {
    pub id: usize,
    pub name: String,
    pub args: Vec<TypedIdentifier>,
    pub returns: Type,
}

impl From<Function> for HoistedFunctionSignature {
    fn from(value: Function) -> Self {
        HoistedFunctionSignature {
            id: value.id,
            name: value.name,
            args: value.args,
            returns: value.returns,
        }
    }
}
#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Statement {
    pub id: usize,
    pub kind: StatementKind,
}

#[derive(Debug, Clone, PartialEq, VariantToStr, ASTStructuralEq)]
pub enum StatementKind {
    // initial pass
    /// Variable initialisation
    Initialisation(Initialisation),
    /// Variable Reassignment
    Reassignment(Reassignment),
    FunctionCall(FunctionCall),
    /// Control-flow return
    Return(Expression),
    /// A tailing expression in a block
    BlockTail(Expression),

    /// A Block of statements
    Block(StatementBlock),
    // CondMatch(Box<ConditionMatch>),

    // after expansion
    ExpandedBlock(ExpandedBlockExpr),
    CondBranch(IfThenElse),
}
#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Initialisation {
    pub id: usize,
    pub kind: InitialisationKind,
}

impl Initialisation {
    pub fn packed(
        id: usize,
        typ: Option<Type>,
        assignee: AssignmentPattern,
        value: Expression,
    ) -> Self {
        Self {
            id,
            kind: InitialisationKind::Packed(PackedInitialisation {
                typ,
                assignee,
                value,
            }),
        }
    }
}

#[derive(Debug, Clone, Eq, PartialEq, ASTStructuralEq)]
pub struct PackedInitialisation {
    pub typ: Option<Type>,
    pub assignee: AssignmentPattern,
    pub value: Expression,
}

/// An assignment to a simple, totally unpacked variable.
#[derive(Debug, Clone, Eq, PartialEq, ASTStructuralEq)]
pub struct UnpackedInitialisation {
    pub typ: Option<Type>,
    pub assignee: String,
    pub value: Expression,
}

#[derive(Debug, Clone, Eq, PartialEq, ASTStructuralEq)]
pub struct PartiallyUnpackedInitialisation {
    pub temporary: UnpackedInitialisation,
    pub unpacked_assignments: Vec<Initialisation>,
}
#[derive(Debug, Clone, Eq, PartialEq, ASTStructuralEq)]
pub enum InitialisationKind {
    Packed(PackedInitialisation),
    PartiallyUnpacked(PartiallyUnpackedInitialisation),
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Reassignment {
    pub id: usize,
    pub assignee: String,
    pub value: Expression,
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct HoistedDeclaration {
    pub id: usize,
    pub typ: Type,
    pub assignee: String,
    pub value: Expression,
}

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct FunctionCall {
    pub id: usize,
    pub name: String,
    pub args: Vec<Expression>,
}
#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct StatementBlock {
    pub id: usize,
    pub statements: Vec<Statement>,
}

impl IntoIterator for StatementBlock {
    type Item = Statement;
    type IntoIter = <Vec<Statement> as IntoIterator>::IntoIter;
    fn into_iter(self) -> Self::IntoIter {
        self.statements.into_iter()
    }
}
impl StatementBlock {
    pub fn as_slice(&self) -> &[Statement] {
        self.statements.as_slice()
    }
}

#[derive(Clone, Debug, PartialEq, ASTStructuralEq)]
pub struct ExpandedBlockExpr {
    /// The label that the block expression has its value assigned to
    /// i.e. `__block0`, `__block1` etc.
    /// This label must be unique to the scope of the function in which it exists
    pub id: usize,
    pub statements: Vec<Statement>,
    pub last: Expression,
}

// macro_rules! extended {
//     ($($first:expr),+) => {{
//         vec![$($first),+]
//     }};
//     ($($first:expr),+ ; $($rest:expr),+) => {{
//         let mut v = vec![$($first),+];
//         $(v.extend($rest);)+
//         v
//     }};
//
//     (; $($rest:expr),+) => {{
//         let mut v = Vec::new();
//         $(v.extend($rest);)+
//         v
//     }};
// }

#[derive(Debug, Clone, HashEqById, ASTStructuralEq)]
pub struct Expression {
    pub id: usize,
    pub kind: ExpressionKind,
}

impl Expression {
    pub fn label_member_access(e: Expression, field: usize) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::MemberAccess(Box::new(e), format!("_{field}")),
        }
    }

    pub fn ident(ident: String) -> Expression {
        Expression {
            id: 0,
            kind: ExpressionKind::Ident(ident),
        }
    }
}

#[derive(Debug, Clone, PartialEq, VariantToStr, ASTStructuralEq)]
pub enum ExpressionKind {
    // initial pass
    Unit,
    IntegerLiteral(u64),
    BoolLiteral(bool),
    FloatLiteral(f64),
    StringLiteral(String),
    Ident(String),
    FuncCall(FunctionCall),
    BinOpExpr(BinOp, Box<Expression>, Box<Expression>),
    UnOpExpr(UnOp, Box<Expression>),
    MemberAccess(Box<Expression>, String),
    CondBranch(IfThenElse),

    Block(StatementBlock),
    // PatternMatch(PatternMatch),
    // ConditionMatch(ConditionMatch),
    // IfThenElse(IfThenElse),

    // after expansion
    ExpandedBlock(Box<ExpandedBlockExpr>),
}

impl Expression {
    pub fn unit(id: usize) -> Self {
        Expression {
            id,
            kind: ExpressionKind::Unit,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, ASTStructuralEq)]
pub enum BinOp {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    LogAnd,
    LogOr,
    LogXor,
    BitAnd,
    BitOr,
    BitXor,
    Subscript,
    Lsh,
    Rsh,
    Eq,
    Neq,
    Geq,
    Leq,
    LT,
    GT,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, ASTStructuralEq)]
pub enum UnOp {
    Neg,
    LogNot,
    BitNot,
}

#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct ConditionMatch {
    pub id: usize,
    conditions: Vec<ConditionMatchArm>,
}

#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct PatternMatch {
    pub id: usize,
    subject: Box<Expression>,
    patterns: Vec<PatternMatchArm>,
}

#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct IfThenElse {
    pub id: usize,
    pub condition: Box<Expression>,
    pub true_case: Box<Expression>,
    pub false_case: Option<Box<Expression>>,
}
#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct PatternMatchArm {
    pub id: usize,
    pat: AssignmentPattern,
    value: Box<Expression>,
}
#[derive(Clone, Debug, HashEqById, ASTStructuralEq)]
pub struct ConditionMatchArm {
    pub id: usize,
    case: Box<Expression>,
    value: Box<Expression>,
}
/// the left hand side of an assignment
///
/// The simplest is a basic identifier
#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum AssignmentPattern {
    /// the pattern
    ///
    /// `var a: ...`
    ///
    /// or
    ///
    /// `a := ...`
    Identifier(String),
    /// the pattern
    ///
    /// `(<pat>, <pat>, <pat>) := ...`
    ///
    /// or
    ///
    /// `var (a,b,c) := ...`
    Tuple(Vec<AssignmentPattern>),
}

// This manual impl exists because deriving it
// causes the compiler to say that the bound `&Vec<AssignmentPattern>: StructuralEq`
// is not satisfied, even though it is???
impl StructuralEq for AssignmentPattern {
    fn structural_eq(&self, other: &Self) -> bool {
        match (self, other) {
            (AssignmentPattern::Identifier(s1), AssignmentPattern::Identifier(s2)) if s1 == s2 => {
                true
            }
            (AssignmentPattern::Tuple(t1), AssignmentPattern::Tuple(t2)) => {
                t1.iter().zip(t2).all(|(a, b)| a.structural_eq(b))
            }
            _ => false,
        }
    }
}

#[derive(Debug, PartialEq, Clone, Eq, Hash)]
pub enum MatchPattern {
    /// the pattern `a => ...`
    Identifier(String),
    /// the pattern `(<pat>, <pat>, ...) => ...`
    Tuple(Vec<AssignmentPattern>),

    UnionVariant(String, String, Box<AssignmentPattern>),
}

impl StructuralEq for MatchPattern {
    fn structural_eq(&self, other: &Self) -> bool {
        match (self, other) {
            (MatchPattern::Identifier(s1), MatchPattern::Identifier(s2)) if s1 == s2 => true,
            (MatchPattern::Tuple(t1), MatchPattern::Tuple(t2)) => t1
                .iter()
                .zip(t2)
                .all(|(a, b)| StructuralEq::structural_eq(a, b)),
            (MatchPattern::UnionVariant(s1, s2, s3), MatchPattern::UnionVariant(o1, o2, o3)) => {
                (s1 == o1) && (s2 == o2) && (StructuralEq::structural_eq(s3.as_ref(), o3.as_ref()))
            }
            _ => false,
        }
    }
}

impl std::fmt::Display for AssignmentPattern {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        let s = match self {
            AssignmentPattern::Identifier(s) => s.clone(),
            AssignmentPattern::Tuple(tups) => {
                let s: Vec<String> = tups.iter().map(|pat| pat.to_string()).collect();
                format!("({})", s.join(", "))
            }
        };
        write!(f, "{}", s)
    }
}

/// The Zea named Struct type / product type
pub struct StructDefinition {
    name: String,
    members: Vec<TypedIdentifier>,
}

pub struct TupleSignature {
    members: Vec<Type>,
}

pub struct Union {
    pub name: String,
    pub members: Vec<UnionVariant>,
}

pub enum UnionVariant {
    Tag(String),
    Type(TypedIdentifier),
}

/// The Type that is bundled with a:
/// - function parameter
/// - identifier in declaration(-assignments)
#[derive(PartialEq, Eq, Clone, Hash, ASTStructuralEq)]
pub enum Type {
    /// Int, Bool, etc.
    Basic(String),

    /// `<type>&`
    Pointer(Box<Type>),
    /// `[<type>]`
    ArrayOf(Box<Type>),
    // /// `&[<type>]`
    // Slice(Box<Type>),
    // /// `?<type>`
    // Option(Box<Type>),
}

impl Debug for Type {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let str = match self {
            Type::Basic(typ) => typ,
            Type::ArrayOf(arr) => &format!("[{arr:?}]"),
            // Type::Option(opt) => &format!("?{opt:?}"),
            Type::Pointer(ptr) => &format!("&{ptr:?}"),
            // Type::Slice(slice) => &format!("&[{slice:?}]"),
        };

        write!(f, "{}", str)
    }
}

impl From<&str> for Type {
    fn from(val: &str) -> Self {
        Type::Basic(val.into())
    }
}

impl From<String> for Type {
    fn from(val: String) -> Self {
        Type::Basic(val)
    }
}
#[allow(non_snake_case)]
impl Type {
    pub fn I64() -> Self {
        Self::from("I64")
    }
    pub fn F64() -> Self {
        Self::from("F64")
    }

    pub fn Bool() -> Self {
        Self::from("Bool")
    }
    pub fn Unit() -> Self {
        Self::from("Unit")
    }

    pub fn Exit() -> Self {
        Self::from("!EXIT!")
    }
}
#[derive(Debug, Eq, PartialEq, Hash, Clone, ASTStructuralEq)]
pub struct TypedIdentifier {
    pub name: String,
    pub typ: Type,
}

impl TypedIdentifier {
    pub fn new(typ: Type, name: impl Into<String>) -> Self {
        Self {
            typ,
            name: name.into(),
        }
    }
}
