//! This module contains the lowering of Immediate-Parsed-Representation (IPR) into Typed-Highlevel-Representation (THR)
//! The main difference between these two is that IPR is a tree of [`Box`]'es,
//! whereas THR has a bunch of interning tables that hold its nodes, and instead of [`Box`]'es,
//! you have indices into the interning tables.
//!
//! The interning tables are instatiations of the [`InternTable<Key, Value>`] generic type,
//! which is itself an ergonomic wrapper around an [`IndexSet`].
//! The `Key` is often a newtype wrapper around [`usize`].
//!
//!
//! The two structs that play a key role in the lowering process are [`THRInternTables`] and [`IPRLoweringContext`]:
//! - [`IPRLoweringContext`] contains an [`IPRModule`] along with all the hashmaps generated by visitor passes,
//!   like type information, identifier resolution etc., everything necessary to infer all properties of a given node.
//! - [`THRInternTables`] contains a bunch of interning tables for :
//!     - types
//!     - symbols
//!     - expressions
//!     - statements
//!     - control-flow-blocks.
//!
//! An [`IPRModule`] can be lowered into THR by using the [`lower_module`] function,
//! which (should be?) infallible
//! as every prior visitor pass validates some set of properties of the AST.
//!
//! the [`lower_module`] call will construct an [`THRModule`], which contains the [`THRInternTables`],
//! and the ID of the synthesized block that instantiate the global variables.
//!
//! Any `lower_[node]()` method of the [`THRInternTables`] will guarantee the following:
//! - After the call returns, all descendant nodes of the supplied node will be interned
//! - An ID (or ID's) will be returned which points to the lowered version of the supplied node.
//!
//! The returned ID is used for constructing nodes wihch hold references,
//! like the `.value` or `.symbol` field in an [`THRInit`].
//!
//! At this stage, structs are also lowered into [`THRStructLayout`]'s,
//! from which you can get byte-offsets for fields, their size and alignment
//!
//! What the THR does not directly provide is a control flow graph (CFG),
//! This is done by a later visitor pass, which provides a way to get the pred- and successors of a [`THRBlock`],
//! which is then used by QBE or some other backend to generate its CFG.

use std::alloc::Layout;

use indexmap::Equivalent;
use zea_internal_macros::{InternKey, VariantToStr};

use zea_common::{CompilerError, CompilerErrorKind, CompilerStage};
macro_rules! internal_compiler_error {
    (spi) => {
        unreachable!(
            "{}",
            CompilerError::new(CompilerStage::IPRtoTHR, CompilerErrorKind::StrayPackedInit)
                .pretty()
        )
    };
    (sui) => {
        unreachable!(
            "{}",
            CompilerError::new(
                CompilerStage::IPRtoTHR,
                CompilerErrorKind::StrayUnscopedIdent
            )
            .pretty()
        )
    };
}
use crate::{
    InternTable,
    zea::{
        BinOp, UnOp,
        ipr::{
            IPRBlockExpression, IPRExpression, IPRExpressionKind, IPRFunction,
            IPRInitializationBlock, IPRInitializationKind, IPRModule, IPRSimpleInitialization,
            IPRStatement, IPRStatementKind, IPRTypeSpecifier, IPRTypedIdentifier,
        },
        visitors::{altering::IdentifierScoper, annotating::SymbolKind},
    },
};

use super::{ipr, typecheck::IPRModuleTypeInfo};

pub fn lower_module(
    module: IPRModule,
    types: IPRModuleTypeInfo,
    ident_scopes: IdentifierScoper,
) -> THRModule {
    let thr_ctx = THRInternTables::with_integer_types();
    let ipr_ctx = IPRLoweringContext {
        module,
        types,
        ident_scopes,
        cf_stack: vec![],
    };
    thr_ctx.lower_module(&ipr_ctx)
}

#[derive(InternKey, Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct THRTypeID(usize);

impl THRTypeID {
    fn alignment(self, ctx: &THRInternTables) -> u64 {
        let ty = ctx
            .types
            .get_by_id(self)
            .expect("struct field name should be interned at this point");
        match ty {
            THRTypeSpecifier::Integer { width, signed: _ } => *width as u64,
            THRTypeSpecifier::Float { width } => *width as u64,
            THRTypeSpecifier::Pointer(inner) => inner.alignment(ctx),
            THRTypeSpecifier::Boolean => 1,
            THRTypeSpecifier::Unit => 0,
            THRTypeSpecifier::Never => 0,
            THRTypeSpecifier::Struct { name: _, layout } => layout.alignment(ctx),
            THRTypeSpecifier::Tuple(layout) => layout.alignment(ctx),
        }
    }

    fn width(self, ctx: &THRInternTables) -> u64 {
        let ty = ctx
            .types
            .get_by_id(self)
            .expect("struct field name should be interned at this point");
        match ty {
            THRTypeSpecifier::Integer { width, signed: _ } => *width as u64,
            THRTypeSpecifier::Float { width } => *width as u64,
            THRTypeSpecifier::Pointer(inner) => inner.width(ctx),
            THRTypeSpecifier::Boolean => 1,
            THRTypeSpecifier::Unit => 0,
            THRTypeSpecifier::Never => 0,
            THRTypeSpecifier::Struct { name: _, layout } => layout.width(ctx),
            THRTypeSpecifier::Tuple(layout) => layout.width(ctx),
        }
    }
}
#[derive(InternKey, Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct THRExprID(usize);
#[derive(InternKey, Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct THRSymbolID(usize);
#[derive(InternKey, Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct THRStatementID(usize);
#[derive(InternKey, Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct THRBlockID(usize);
#[derive(InternKey, Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct THRFunctionID(usize);

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct THRModule {
    interned: THRInternTables,
    global_data_block: THRBlockID,
    entry_point: THRFunctionID,
    pub name: String,
}

impl THRModule {
    pub fn global_data_block(&self) -> THRBlockID {
        self.global_data_block
    }

    pub fn entry_point(&self) -> THRFunctionID {
        self.entry_point
    }

    pub fn get_block(&self, block: THRBlockID) -> &THRBlock {
        self.interned.blocks.get_by_id(block).unwrap()
    }
    pub fn get_type(&self, typ: THRTypeID) -> &THRTypeSpecifier {
        self.interned.types.get_by_id(typ).unwrap()
    }
    pub fn get_function(&self, func: THRFunctionID) -> &THRFunction {
        self.interned.functions.get_by_id(func).unwrap()
    }
    pub fn functions(&self) -> &InternTable<THRFunctionID, THRFunction> {
        &self.interned.functions
    }
    pub fn get_symbol(&self, symbol: THRSymbolID) -> &THRSymbol {
        self.interned.symbols.get_by_id(symbol).unwrap()
    }
    pub fn get_statement(&self, stmt: THRStatementID) -> &THRStatement {
        self.interned.statements.get_by_id(stmt).unwrap()
    }
    pub fn get_expr(&self, expr: THRExprID) -> &THRExpression {
        self.interned.expressions.get_by_id(expr).unwrap()
    }
    pub fn alignment_of_layout(&self, typ: &THRStructLayout) -> u64 {
        typ.alignment(&self.interned)
    }
    pub fn width_of(&self, typ: THRTypeID) -> u64 {
        typ.width(&self.interned)
    }

    pub fn alignment_of(&self, typ: THRTypeID) -> u64 {
        typ.alignment(&self.interned)
    }
}

#[derive(Clone, PartialEq, Eq, Default)]
pub struct THRInternTables {
    expressions: InternTable<THRExprID, THRExpression>,
    symbols: InternTable<THRSymbolID, THRSymbol>,
    types: InternTable<THRTypeID, THRTypeSpecifier>,
    statements: InternTable<THRStatementID, THRStatement>,
    blocks: InternTable<THRBlockID, THRBlock>,
    functions: InternTable<THRFunctionID, THRFunction>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IntegerWidth {
    _8 = 1,
    _16 = 2,
    _32 = 4,
    _64 = 8,
}

impl TryFrom<usize> for IntegerWidth {
    type Error = usize;
    fn try_from(value: usize) -> Result<Self, Self::Error> {
        match value {
            8 => Ok(Self::_8),
            16 => Ok(Self::_16),
            32 => Ok(Self::_32),
            64 => Ok(Self::_64),
            _ => Err(value),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FloatWidth {
    _32 = 4,
    _64 = 8,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum THRTypeSpecifier {
    Integer {
        width: IntegerWidth,
        signed: bool,
    },
    Float {
        width: FloatWidth,
    },
    Pointer(THRTypeID),
    Boolean,
    Unit,
    Never,
    Struct {
        name: String,
        layout: THRStructLayout,
    },
    Tuple(THRStructLayout),
}

impl THRTypeSpecifier {
    pub const fn i_signed(width: IntegerWidth) -> Self {
        Self::Integer {
            width,
            signed: true,
        }
    }
    pub const fn i_unsigned(width: IntegerWidth) -> Self {
        Self::Integer {
            width,
            signed: false,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct THRStructLayout {
    pub ordering: StructOrdering,
    pub fields: Vec<THRStructField>,
}
impl THRStructLayout {
    pub fn alignment(&self, ctx: &THRInternTables) -> u64 {
        self.fields
            .iter()
            .map(|field| field.typ.alignment(ctx))
            .max()
            .unwrap_or(0)
    }

    pub fn width(&self, ctx: &THRInternTables) -> u64 {
        let struct_alignment = self.alignment(ctx);
        let summed_fields = self.fields.iter().map(|f| f.typ.width(ctx)).sum();
        Self::next_aligned_offset(summed_fields, struct_alignment)
    }

    /// calculate the closest multiple `m` of `required_alignment` s.t. `m >= cur_offset` && `m % required_alignment == 0`
    fn next_aligned_offset(cur_offset: u64, required_alignment: u64) -> u64 {
        match (cur_offset, required_alignment) {
            (0, _) => 0,
            (c, a) => {
                if c > a {
                    let (div, rem) = div_rem(c, a);
                    if rem != 0 { (div + 1) * a } else { div * a }
                } else {
                    a
                }
            }
        }
    }
}

fn div_rem(x: u64, y: u64) -> (u64, u64) {
    let quot = x.checked_div_euclid(y).unwrap_or(0);
    let rem = x.checked_rem_euclid(y).unwrap_or(0);
    (quot, rem)
}
/// Specify the ordering of a [`THRStructLayout`], note that fields are always aligned
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum StructOrdering {
    /// Do not reorder fields
    Naive,
    /// Order fields in descending size
    Descending,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct THRStructField {
    pub name: String,
    pub typ: THRTypeID,
    pub offset: usize,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum THRExpression {
    ConstInt(TypedLiteral<u64>),
    ConstFloat(TypedLiteral<f64>),
    ConstBool(bool),
    Binop(BinOp, THRExprID, THRExprID),
    Unop(UnOp, THRExprID),
    Ident(THRSymbolID),
}

impl THRExpression {
    pub const fn const_int(value: u64, typ: THRTypeID) -> THRExpression {
        let literal = TypedLiteral { value, typ };
        THRExpression::ConstInt(literal)
    }
    pub const fn binop(op: BinOp, lhs: THRExprID, rhs: THRExprID) -> THRExpression {
        Self::Binop(op, lhs, rhs)
    }
}

/// used to provide an Eq and Hash impl for floats.
pub trait NumericLiteral: Copy + Clone + PartialEq {
    fn canonical(&self) -> Self;
}

impl NumericLiteral for u64 {
    fn canonical(&self) -> Self {
        *self
    }
}

impl NumericLiteral for f64 {
    fn canonical(&self) -> Self {
        if self.is_nan() { f64::NAN } else { *self }
    }
}
impl NumericLiteral for bool {
    fn canonical(&self) -> Self {
        *self
    }
}

#[derive(Debug, Clone, Copy)]
pub struct TypedLiteral<T: NumericLiteral> {
    pub typ: THRTypeID,
    pub value: T,
}

impl<T: NumericLiteral> PartialEq for TypedLiteral<T> {
    fn eq(&self, other: &Self) -> bool {
        self.typ == other.typ && self.value.canonical() == other.value.canonical()
    }
}
impl<T: NumericLiteral> Eq for TypedLiteral<T> {}

impl std::hash::Hash for TypedLiteral<f64> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.typ.hash(state);
        self.value.canonical().to_bits().hash(state);
    }
}
impl std::hash::Hash for TypedLiteral<u64> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.typ.hash(state);
        self.value.hash(state);
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct THRBlock {
    pub items: Vec<THRStatementID>,
}

enum THRLoweredStatement {
    Single(THRStatementID),
    Multiple(THRBlockID),
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, VariantToStr)]
pub enum THRStatement {
    Init(THRSymbolDecl, THRExprID),
    Jmp(THRBlockID),
    Ret(THRExprID),
    /// An assigment that is initialized by some branch,
    /// all branches must terminate with a [`SegmentReturn`]
    SegmentedAssign(THRSymbolDecl, Vec<THRBlockID>),
    /// An instruction that signals a return,
    /// except that it is paired to some [`SegmentedAssign`]
    SegmentReturn(THRSymbolID, THRExprID),
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct THRSymbolDecl {
    pub symbol: THRSymbolID,
    pub typ: THRTypeID,
}
impl THRSymbolDecl {
    fn new(symbol: THRSymbolID, typ: THRTypeID) -> Self {
        Self { symbol, typ }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct THRFunction {
    pub name: String,
    pub params: Vec<THRSymbolDecl>,
    pub body: THRBlockID,
    pub ret: THRTypeID,
}

impl THRFunction {
    pub fn new(name: String, params: Vec<THRSymbolDecl>, body: THRBlockID, ret: THRTypeID) -> Self {
        Self {
            name,
            params,
            body,
            ret,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct THRSymbol {
    pub name: String,
    pub kind: SymbolKind,
}

impl THRSymbol {
    pub fn new(name: String, kind: SymbolKind) -> Self {
        Self { name, kind }
    }
    pub fn func_param(name: String) -> Self {
        Self::new(name, SymbolKind::FunctionParam)
    }
    pub fn local(name: String) -> Self {
        Self::new(name, SymbolKind::LocalVar)
    }
}

static THR_INTEGER_TYPES: [THRTypeSpecifier; 8] = [
    THRTypeSpecifier::i_signed(IntegerWidth::_8),
    THRTypeSpecifier::i_signed(IntegerWidth::_16),
    THRTypeSpecifier::i_signed(IntegerWidth::_32),
    THRTypeSpecifier::i_signed(IntegerWidth::_64),
    THRTypeSpecifier::i_unsigned(IntegerWidth::_8),
    THRTypeSpecifier::i_unsigned(IntegerWidth::_16),
    THRTypeSpecifier::i_unsigned(IntegerWidth::_32),
    THRTypeSpecifier::i_unsigned(IntegerWidth::_64),
];

enum LoweredMaybeSegmentedExpr {
    Segmented(Vec<THRBlockID>),
    NotSegmented(THRExprID),
}

impl THRInternTables {
    pub fn with_integer_types() -> Self {
        let mut s = Self::default();
        for t in THR_INTEGER_TYPES.as_slice() {
            s.types.intern(t.clone());
        }
        s
    }

    fn lower_type(
        &mut self,
        _ipr_ctx: &IPRLoweringContext,
        iprtype: &IPRTypeSpecifier,
    ) -> THRTypeID {
        let t = match iprtype {
            IPRTypeSpecifier::NonScalar(_a) => {
                todo!();
                // let s = ctx
                //     .struct_definitions
                //     .iter()
                //     .find(|s| s.name == *a)
                //     .expect("type checking should resolve struct names");
                // for IPRTypedIdentifier { name, typ } in s.members.iter() {
                //     let typ = self.lower_type(typ, ctx);
                //     let field = THRStructField {
                //         name: name.clone(),
                //         typ,
                //         offset: 0,
                //     };
                // }

                // todo!()
            }
            IPRTypeSpecifier::Unit => THRTypeSpecifier::Unit,
            IPRTypeSpecifier::Bool => THRTypeSpecifier::Boolean,
            IPRTypeSpecifier::Integer { width, signed } => {
                let width = IntegerWidth::try_from(*width)
                    .unwrap_or_else(|_| panic!("illegal integer width: {width}"));
                if *signed {
                    THRTypeSpecifier::i_signed(width)
                } else {
                    THRTypeSpecifier::i_unsigned(width)
                }
            }
            IPRTypeSpecifier::Float { width: _ } => todo!(),
            IPRTypeSpecifier::Pointer(inner) => {
                let inner_id = self.lower_type(_ipr_ctx, inner);
                THRTypeSpecifier::Pointer(inner_id)
            }
            IPRTypeSpecifier::ArrayOf(_) => todo!(),
            IPRTypeSpecifier::Never => THRTypeSpecifier::Never,
        };
        self.types.intern(t)
    }

    fn lower_expression(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        expr: &IPRExpression,
    ) -> THRExprID {
        let ipr_t = ipr_ctx.types.lookup(expr.id);
        let thr_t = self.lower_type(ipr_ctx, ipr_t);
        let node = match &expr.kind {
            IPRExpressionKind::Unit => todo!(),
            IPRExpressionKind::IntegerLiteral(i) => THRExpression::const_int(*i as u64, thr_t),
            IPRExpressionKind::BoolLiteral(b) => THRExpression::ConstBool(*b),
            IPRExpressionKind::FloatLiteral(_) => todo!(),
            IPRExpressionKind::StringLiteral(_) => todo!(),
            IPRExpressionKind::ScopedIdent(i) => {
                let symbol = THRSymbol {
                    name: i.ident.clone(),
                    kind: i.kind,
                };
                let symbol = self.symbols.intern(symbol);
                THRExpression::Ident(symbol)
            }
            IPRExpressionKind::FunctionCall(_iprfunction_call) => {
                todo!()
            }
            IPRExpressionKind::BinOpExpr(op, l, r) => {
                let l = self.lower_expression(ipr_ctx, l.as_ref());
                let r = self.lower_expression(ipr_ctx, r.as_ref());
                THRExpression::binop(*op, l, r)
            }
            IPRExpressionKind::UnOpExpr(_op, _arg) => {
                todo!()
            }
            IPRExpressionKind::MemberAccess(_iprexpression, _) => {
                todo!()
            }
            IPRExpressionKind::IfThenElse(_iprbranch) => {
                todo!()
            }
            IPRExpressionKind::Block(_b) => todo!(),
            IPRExpressionKind::UnScopedIdent(_) => internal_compiler_error!(sui),
        };
        self.expressions.intern(node)
    }

    fn lower_stmt(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        stmt: &IPRStatement,
    ) -> THRLoweredStatement {
        match &stmt.kind {
            IPRStatementKind::Initialization(init) => {
                let ids = self.lower_init_block(ipr_ctx, init, SymbolKind::LocalVar);
                if ids.len() == 1 {
                    let id = ids[0];
                    THRLoweredStatement::Single(id)
                } else {
                    let block = THRBlock { items: ids };
                    let block = self.blocks.intern(block);
                    THRLoweredStatement::Multiple(block)
                }
            }
            IPRStatementKind::Reassignment(_iprreassignment) => {
                todo!()
            }
            IPRStatementKind::FunctionCall(_iprfunction_call) => {
                todo!()
            }
            IPRStatementKind::Return(_iprexpression) => {
                todo!()
            }
            IPRStatementKind::Block(_iprblock_expression) => {
                todo!()
            }
            IPRStatementKind::IfThenElse(_iprbranch) => {
                todo!()
            }
        }
    }

    fn lower_init_block(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        init_block: &IPRInitializationBlock,
        kind: SymbolKind,
    ) -> Vec<THRStatementID> {
        let IPRInitializationKind::Unpacked(inits) = &init_block.kind else {
            internal_compiler_error!(spi)
        };
        inits
            .iter()
            .map(|init| self.lower_init(ipr_ctx, init, kind))
            .collect()
    }

    fn lower_init(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        init: &IPRSimpleInitialization,
        kind: SymbolKind,
    ) -> THRStatementID {
        let symbol = THRSymbol {
            name: init.assignee.clone(),
            kind,
        };
        let symbol = self.symbols.intern(symbol);
        let value = self.lower_expression_maybe_segmented(ipr_ctx, &init.value, symbol);
        let typ = init.typ.as_ref().unwrap();
        let typ = self.lower_type(ipr_ctx, typ);

        let init = THRSymbolDecl { symbol, typ };
        let stmt = match value {
            LoweredMaybeSegmentedExpr::Segmented(block) => {
                THRStatement::SegmentedAssign(init, block)
            }
            LoweredMaybeSegmentedExpr::NotSegmented(expr) => THRStatement::Init(init, expr),
        };
        self.statements.intern(stmt)
    }

    fn lower_module(mut self, ipr_ctx: &IPRLoweringContext) -> THRModule {
        let globs = &ipr_ctx.module.global_vars;
        let mut items = vec![];
        for glob in globs.iter() {
            let ids = self.lower_init_block(ipr_ctx, glob, SymbolKind::GlobalVar);
            items.extend(ids);
        }
        let global_data_block = THRBlock { items };
        let global_data_block = self.blocks.intern(global_data_block);

        let funcs = &ipr_ctx.module.functions;
        let mut entry_point = None;
        for f in funcs.iter() {
            let func_id: THRFunctionID = self.lower_function(ipr_ctx, f);
            if f.name == "main" {
                entry_point = Some(func_id);
            }
        }

        THRModule {
            interned: self,
            global_data_block,
            entry_point: entry_point.expect("missing entry point"),
            name: ipr_ctx.module.name.clone(),
        }
    }

    fn lower_function(&mut self, ipr_ctx: &IPRLoweringContext, f: &IPRFunction) -> THRFunctionID {
        let mut params = vec![];
        for param in f.params.iter() {
            let symbol = THRSymbol::func_param(param.name.clone());
            let symbol = self.symbols.intern(symbol);

            let typ = self.lower_type(ipr_ctx, &param.typ);

            let param = THRSymbolDecl::new(symbol, typ);
            params.push(param);
        }
        let body: THRBlockID = self.lower_block(ipr_ctx, &f.body);
        let ret = self.lower_type(ipr_ctx, &f.returns);
        let f = THRFunction::new(f.name.clone(), params, body, ret);
        self.functions.intern(f)
    }

    fn lower_block(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        body: &IPRBlockExpression,
    ) -> THRBlockID {
        let mut items: Vec<THRStatementID> = vec![];

        for stmt in body.statements.iter() {
            match self.lower_stmt(ipr_ctx, stmt) {
                THRLoweredStatement::Single(stmt_id) => {
                    items.push(stmt_id);
                }
                THRLoweredStatement::Multiple(block_id) => {
                    let stmt = THRStatement::Jmp(block_id);
                    let stmt = self.statements.intern(stmt);
                    items.push(stmt);
                }
            }
        }
        let tail = self.lower_expression(ipr_ctx, &body.tail);
        let tail = THRStatement::Ret(tail);
        let tail = self.statements.intern(tail);
        items.push(tail);
        let b = THRBlock { items };
        self.blocks.intern(b)
    }

    /// lower some block that is one of the branches of a segmented init:
    /// ```ignore
    /// x := {y:= 5; y};
    ///
    /// ```
    /// with the equivalent IPR:
    /// ```ignore
    /// Init {
    ///   "x"
    ///   Block {
    ///     Init {
    ///       "y"
    ///       5
    ///     },
    ///     BlockTail { Ident "y"}
    ///   }
    /// }
    /// ```
    /// which would be lowered into the THR
    /// ```ignore
    /// symbol 0 : local x
    /// symbol 1 : local y
    ///
    /// expr 0 : literal<u8> 5
    /// expr 1 : ident symbol 1
    ///
    /// block 0 (global) : {
    ///   segmented-init symbol 0 [block 1]
    /// }
    ///
    /// block 1 : {
    ///   init (symbol 1 expr 0)
    ///   phi-return (block 0 expr 1)
    /// }
    /// ```
    /// that is, the block needs to terminate with an assignment to the target symbol
    fn lower_block_segmented(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        block: &IPRBlockExpression,
        target_symbol: THRSymbolID,
    ) -> THRBlockID {
        let mut items: Vec<THRStatementID> = vec![];

        for stmt in block.statements.iter() {
            match self.lower_stmt(ipr_ctx, stmt) {
                THRLoweredStatement::Single(stmt_id) => {
                    items.push(stmt_id);
                }
                THRLoweredStatement::Multiple(block_id) => {
                    let stmt = THRStatement::Jmp(block_id);
                    let stmt = self.statements.intern(stmt);
                    items.push(stmt);
                }
            }
        }
        let last = self.lower_expression(ipr_ctx, &block.tail);
        let segment = THRStatement::SegmentReturn(target_symbol, last);
        let segment = self.statements.intern(segment);
        items.push(segment);
        let b = THRBlock { items };
        self.blocks.intern(b)
    }

    fn lower_expression_maybe_segmented(
        &mut self,
        ipr_ctx: &IPRLoweringContext,
        expr: &IPRExpression,
        target_symbol: THRSymbolID,
    ) -> LoweredMaybeSegmentedExpr {
        match &expr.kind {
            IPRExpressionKind::Block(block) => {
                LoweredMaybeSegmentedExpr::Segmented(vec![self.lower_block_segmented(
                    ipr_ctx,
                    block,
                    target_symbol,
                )])
            }
            IPRExpressionKind::IfThenElse(_iprbranch) => todo!(),
            _ => LoweredMaybeSegmentedExpr::NotSegmented(self.lower_expression(ipr_ctx, expr)),
        }
    }
}

struct IPRLoweringContext {
    module: IPRModule,
    types: IPRModuleTypeInfo,
    ident_scopes: IdentifierScoper,
    cf_stack: Vec<THRBlockID>,
}

impl std::fmt::Debug for THRInternTables {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&"TYPES:\n\t", f)?;
        for (i, t) in self.types.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            t.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }

        std::fmt::Display::fmt(&"\rSYMBOLS:\n\t", f)?;
        for (i, s) in self.symbols.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        std::fmt::Display::fmt(&"\rEXPRESSIONS:\n\t", f)?;
        for (i, s) in self.expressions.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        std::fmt::Display::fmt(&"\rSTATEMENTS:\n\t", f)?;
        for (i, s) in self.statements.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        std::fmt::Display::fmt(&"\rBLOCKS:\n\t", f)?;
        for (i, s) in self.blocks.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        std::fmt::Display::fmt(&"\rFUNCTIONS:\n\t", f)?;
        for (i, s) in self.functions.iter().enumerate() {
            i.fmt(f)?;
            std::fmt::Display::fmt(&"\t", f)?;
            s.fmt(f)?;
            std::fmt::Display::fmt(&"\n\t", f)?;
        }
        "\n".fmt(f)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn struct_field(ctx: &mut THRInternTables, typ: THRTypeSpecifier) -> THRStructField {
        THRStructField {
            name: "".to_string(),
            typ: ctx.types.intern(typ),
            offset: 0,
        }
    }
    fn struct_field_i8(ctx: &mut THRInternTables) -> THRStructField {
        struct_field(ctx, THRTypeSpecifier::i_signed(IntegerWidth::_8))
    }
    fn struct_field_i32(ctx: &mut THRInternTables) -> THRStructField {
        struct_field(ctx, THRTypeSpecifier::i_signed(IntegerWidth::_32))
    }
    fn struct_field_i64(ctx: &mut THRInternTables) -> THRStructField {
        struct_field(ctx, THRTypeSpecifier::i_signed(IntegerWidth::_64))
    }
    fn struct_field_i16(ctx: &mut THRInternTables) -> THRStructField {
        struct_field(ctx, THRTypeSpecifier::i_signed(IntegerWidth::_16))
    }

    fn struct_size_invariant(layout: &THRStructLayout, ctx: &THRInternTables) {
        let s = layout.width(ctx);
        let a = layout.alignment(ctx);
        assert_eq!(s % a, 0, "size {s} should be a multiple of alignment{a}");
    }
    fn run_layout_cases(
        cases: Vec<(StructOrdering, Vec<THRStructField>, usize, usize)>,
        ctx: &THRInternTables,
    ) {
        for (ordering, fields, size, align) in cases {
            let s = THRStructLayout { ordering, fields };

            assert_eq!(s.width(ctx), size);
            assert_eq!(s.alignment(ctx), align);
            struct_size_invariant(&s, ctx);
        }
    }
    #[test]
    fn struct_width() {
        let mut ctx = THRInternTables::with_integer_types();
        let i8 = struct_field_i8(&mut ctx);
        let i16 = struct_field_i16(&mut ctx);
        let i32 = struct_field_i32(&mut ctx);
        let i64 = struct_field_i64(&mut ctx);

        let basic_cases = [
            (StructOrdering::Naive, vec![i8.clone()], 1usize, 1usize),
            (StructOrdering::Naive, vec![i8.clone(), i8.clone()], 2, 1),
            (
                StructOrdering::Naive,
                vec![i8.clone(), i8.clone(), i8.clone(), i8.clone()],
                4,
                1,
            ),
            (StructOrdering::Naive, vec![i16.clone()], 2, 2),
            (StructOrdering::Naive, vec![i16.clone(), i16.clone()], 4, 2),
            (
                StructOrdering::Naive,
                vec![i16.clone(), i16.clone(), i16.clone(), i16.clone()],
                8,
                2,
            ),
            (StructOrdering::Naive, vec![i32.clone()], 4, 4),
            (StructOrdering::Naive, vec![i32.clone(), i32.clone()], 8, 4),
            (
                StructOrdering::Naive,
                vec![i32.clone(), i32.clone(), i32.clone(), i32.clone()],
                16,
                4,
            ),
            (StructOrdering::Naive, vec![i64.clone()], 8, 8),
            (StructOrdering::Naive, vec![i64.clone(), i64.clone()], 16, 8),
            (
                StructOrdering::Naive,
                vec![i64.clone(), i64.clone(), i64.clone(), i64.clone()],
                32,
                8,
            ),
        ];

        let mixed_fields = [
            (
                StructOrdering::Naive,
                vec![i16.clone(), i8.clone()],
                4usize,
                2usize,
            ),
            (StructOrdering::Naive, vec![i32.clone(), i8.clone()], 8, 4),
            (
                StructOrdering::Naive,
                vec![i32.clone(), i8.clone(), i32.clone()],
                12,
                4,
            ),
            (StructOrdering::Naive, vec![i64.clone(), i8.clone()], 16, 8),
            (StructOrdering::Naive, vec![i64.clone(), i8.clone()], 16, 8),
            (
                StructOrdering::Naive,
                vec![i64.clone(), i8.clone(), i64.clone()],
                24,
                8,
            ),
        ];

        run_layout_cases(basic_cases.to_vec(), &ctx);
        run_layout_cases(mixed_fields.to_vec(), &ctx);
    }
}
